export const PERMISSIONS = {
  BASE_ACCESS: 'api.get.auth_me',

  USERS_READ: 'api.get.users',
  USERS_CREATE: 'api.post.users',
  USERS_INVITATION_RESEND: 'api.post.users_id_invitations_resend',
  IAM_ROLES_READ: 'api.get.admin_iam_roles',
  IAM_PERMISSIONS_READ: 'api.get.admin_iam_permissions',
  IAM_USER_ROLES_READ: 'api.get.admin_iam_users_id_roles',
  IAM_USER_ROLES_WRITE: 'api.put.admin_iam_users_id_roles',

  CUSTOMERS_READ: 'api.get.customers',
  CUSTOMERS_DETAIL_READ: 'api.get.customers_id',
  PRICING_POLICIES_READ: 'api.get.admin_pricing_policies',
  PRICING_SWAP_CONFIG_READ: 'api.get.admin_pricing_policies_swap',
  PRICING_SWAP_CONFIG_WRITE: 'api.put.admin_pricing_policies_swap',
  PRICING_WITHDRAW_CONFIG_READ: 'api.get.admin_pricing_policies_withdrawal',
  PRICING_WITHDRAW_CONFIG_WRITE: 'api.put.admin_pricing_policies_withdrawal',

  // Backward-compatible aliases for existing usages.
  CUSTOMER_SWAP_RATES_READ: 'api.get.admin_pricing_policies',
  CUSTOMER_SWAP_RATES_WRITE: 'api.put.admin_pricing_policies_swap',
  CUSTOMER_SWAP_RATES_EDIT: 'api.put.admin_pricing_policies_withdrawal',

  SWAP_QUOTES_READ: 'api.get.admin_swap_transactions_quotes',
  SWAP_QUOTES_DETAIL_READ: 'api.get.admin_swap_transactions_quotes_id',
  SWAP_TRANSACTIONS_READ: 'api.get.admin_swap_transactions',
  SWAP_TRANSACTION_DETAIL_READ: 'api.get.admin_swap_transactions_id',

  OUTSTANDING_SETTLEMENTS_READ: 'api.get.admin_reconciliation_outstanding_settlements',
  OUTSTANDING_SETTLEMENT_DETAIL_READ:
    'api.get.admin_reconciliation_outstanding_settlements_id',
  OUTSTANDINGS_READ: 'api.get.admin_reconciliation_outstandings',
  OUTSTANDING_DETAIL_READ: 'api.get.admin_reconciliation_outstandings_id',

  CDD_CASES_READ: 'api.get.admin_compliance_cdd_cases',
  EDD_CASES_READ: 'api.get.admin_compliance_edd_cases',
  ALERTS_READ: 'api.get.admin_compliance_alerts',
  ALERTS_WRITE: 'api.patch.admin_compliance_alerts_id_action',
  CASES_READ: 'api.get.admin_compliance_cases',
  CASES_WRITE: 'api.patch.admin_compliance_cases_id_action',
  CASE_EVIDENCE_EXPORTS_READ: 'api.get.admin_compliance_cases_evidence_packages',
  CASE_EVIDENCE_EXPORT_CREATE: 'api.post.admin_compliance_cases_export_evidence_package',
  CASE_EVIDENCE_EXPORT_DETAIL_READ:
    'api.get.admin_compliance_cases_evidence_packages_id',
  CASE_EVIDENCE_EXPORT_DOWNLOAD:
    'api.get.admin_compliance_cases_evidence_packages_id_download',
  INCIDENTS_READ: 'api.get.admin_compliance_incidents',
  INCIDENTS_WRITE: 'api.patch.admin_compliance_incidents_id_action',
  RISK_DECISION_RECORDS_READ: 'api.get.admin_risk_decision_records',
  RISK_DECISION_RECORD_DETAIL_READ: 'api.get.admin_risk_decision_records_id',
  AUDIT_LOGS_READ: 'api.get.admin_audit_logs',
  AUDIT_EXPORT_CREATE: 'api.post.admin_audit_logs_export_evidence_package',
  AUDIT_EVIDENCE_EXPORTS_READ: 'api.get.admin_audit_logs_evidence_packages',
  AUDIT_EVIDENCE_EXPORT_DETAIL_READ: 'api.get.admin_audit_logs_evidence_packages_id',
  AUDIT_EVIDENCE_EXPORT_DOWNLOAD:
    'api.get.admin_audit_logs_evidence_packages_id_download',
  GOV_APPROVALS_READ: 'api.get.admin_control_gates_approvals',
  GOV_APPROVAL_DETAIL_READ: 'api.get.admin_control_gates_approvals_id',
  GOV_APPROVAL_CREATE: 'api.post.admin_control_gates_approvals',
  GOV_APPROVAL_SUBMIT: 'api.post.admin_control_gates_approvals_id_submit',
  GOV_APPROVAL_APPROVE: 'api.post.admin_control_gates_approvals_id_approve',
  GOV_APPROVAL_REJECT: 'api.post.admin_control_gates_approvals_id_reject',
  GOV_APPROVAL_CANCEL: 'api.post.admin_control_gates_approvals_id_cancel',
  GOV_CHANGE_TICKETS_READ: 'api.get.admin_control_gates_change_tickets',
  GOV_CHANGE_TICKET_DETAIL_READ: 'api.get.admin_control_gates_change_tickets_id',
  GOV_CHANGE_TICKET_CREATE: 'api.post.admin_control_gates_change_tickets',
  GOV_CHANGE_TICKET_SUBMIT: 'api.post.admin_control_gates_change_tickets_id_submit',
  GOV_CHANGE_TICKET_RESUBMIT: 'api.post.admin_control_gates_change_tickets_id_resubmit',
  GOV_CHANGE_TICKET_GATE_RUNS_READ: 'api.get.admin_control_gates_change_tickets_id_gate_runs',
  GOV_CHANGE_TICKET_GATE_CHECK: 'api.post.admin_control_gates_change_tickets_id_gate_checks',
  GOV_CHANGE_TICKET_DEPLOY_STATUS:
    'api.post.admin_control_gates_change_tickets_id_deploy_status',
  GOV_CHANGE_TICKET_CLOSE: 'api.post.admin_control_gates_change_tickets_id_close',
  GOV_DELETE_REQUESTS_READ: 'api.get.admin_control_gates_delete_requests',
  GOV_DELETE_REQUEST_DETAIL_READ: 'api.get.admin_control_gates_delete_requests_id',
  GOV_DELETE_REQUEST_CREATE: 'api.post.admin_control_gates_delete_requests',
  GOV_DELETE_REQUEST_SUBMIT: 'api.post.admin_control_gates_delete_requests_id_submit',
  GOV_DELETE_REQUEST_CANCEL: 'api.post.admin_control_gates_delete_requests_id_cancel',
  GOV_DELETE_REQUEST_EXECUTE: 'api.post.admin_control_gates_delete_requests_id_execute',
  GOV_SLA_TIMERS_READ: 'api.get.admin_control_gates_sla_timers',
  GOV_SLA_TIMER_DETAIL_READ: 'api.get.admin_control_gates_sla_timers_id',
  GOV_SLA_TIMER_RECALC: 'api.post.admin_control_gates_sla_timers_id_recalc',
  GOV_SLA_TIMER_CLOSE: 'api.post.admin_control_gates_sla_timers_id_close',

  WALLETS_READ: 'api.get.wallets',
  WALLET_DETAIL_READ: 'api.get.wallets_id',
  PAYINS_READ: 'api.get.treasury_payins',
  PAYIN_DETAIL_READ: 'api.get.treasury_payins_id',
  PAYOUTS_READ: 'api.get.payouts',
  PAYOUT_DETAIL_READ: 'api.get.payouts_id',
  INTERNAL_FUNDS_READ: 'api.get.admin_internal_funds',
  INTERNAL_FUND_DETAIL_READ: 'api.get.admin_internal_funds_id',

  LIQUIDITY_PROVIDERS_READ: 'api.get.liquidity_providers',
  LIQUIDITY_PROVIDERS_CREATE: 'api.post.liquidity_providers',
  LIQUIDITY_CONFIG_READ: 'api.get.liquidity_configurations',
  LIQUIDITY_CONFIG_CREATE: 'api.post.liquidity_configurations',
  LIQUIDITY_CONFIG_UPDATE: 'api.put.liquidity_configurations_id',
  ASSETS_READ: 'api.get.assets',
  ASSETS_CREATE: 'api.post.assets',
  ACCT_EVENTS_READ: 'api.get.acct_events',
  JOURNAL_HEADER_TEMPLATES_READ: 'api.get.journal_header_templates',
  JOURNAL_LINE_TEMPLATES_READ: 'api.get.journal_line_templates',
  CLEARING_TEMPLATES_READ: 'api.get.clearing_templates',

  DEPOSIT_TRANSACTIONS_READ: 'api.get.deposit_transactions',
  DEPOSIT_TRANSACTION_DETAIL_READ: 'api.get.deposit_transactions_id',
  WITHDRAW_TRANSACTIONS_READ: 'api.get.withdraw_transactions',
  WITHDRAW_TRANSACTION_DETAIL_READ: 'api.get.withdraw_transactions_id',
  INTERNAL_TRANSACTIONS_READ: 'api.get.admin_internal_transactions',
  INTERNAL_TRANSACTION_DETAIL_READ: 'api.get.admin_internal_transactions_id',

  COA_READ: 'api.get.coa',
  JOURNALS_READ: 'api.get.journals',
  JOURNAL_DETAIL_READ: 'api.get.journals_id',
  JOURNAL_LINES_READ: 'api.get.journal_lines',
  JOURNAL_LINE_DETAIL_READ: 'api.get.journal_lines_id',
  CUSTOMER_BALANCE_HISTORY_READ: 'api.get.journal_lines_customer_balance_history',

  CLEARINGS_READ: 'api.get.clearings',
  CLEARING_DETAIL_READ: 'api.get.clearings_id',
  CLEARING_LINES_READ: 'api.get.clearings_lines',
  CLEARING_LINE_DETAIL_READ: 'api.get.clearings_lines_id',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
