import { V1_AUDIT_ACTIONS, V4_DEPOSIT_AUDIT_ACTIONS, V5_WITHDRAW_AUDIT_ACTIONS, V6_SWAP_AUDIT_ACTIONS, V8_RECON_AUDIT_ACTIONS, DEPRECATED_AUDIT_ACTIONS } from './audit-actions.constant';
import { AuditCorrelationMode } from '../dto/audit-log.dto';

describe('第一批 · V1 词表守则', () => {
  const codes = Object.keys(V1_AUDIT_ACTIONS);

  it('恰好 101 个码（首铸 45 + 站7 收编 22：治理 18 + 平台运营 4 − Task5(2026-08-30/31)退役 19：'
    + '监管闸门7+五本档案簿10+LP配置1+手工建户1，剩 APPROVAL_REQUIRED_MISSING/WALLET_STATUS_UPDATED/FUNDS_ORDER_ADVANCED，得 48；'
    + '+ 2 ADMIN_ACCESS_DENIED/APPROVAL_TIMEOUT_SIMULATED（此前未同步本断言的历史遗漏）；'
    + '+ 16 Task12(2026-09-01) SWAP/WITHDRAWAL_FEE_LEVEL_CREATION/CHANGE 四族裸名换前缀唯一新码，得 66；'
    + '+ 12 Task13(2026-09-01) 资产四族：6 码值不变只进合同（ASSET_CREATED_AND_PROVISIONED/ASSET_CREATION_FAILED/'
    + 'ASSET_PROVISIONING_UPDATED/ASSET_ACTIVATED/ASSET_SUSPENDED/ASSET_REACTIVATED）'
    + '+ 6 裸名换前缀唯一新码（SUSPENSION_/REACTIVATION_/ACTIVATION_ 各 REQUESTED+FAILED），得 78；'
    + '+ 11 Task14(2026-09-02) 限额两族 + 客户标签 + L1 拦截码：TRANSACTION_LIMIT_CREATION_/'
    + 'TRANSACTION_LIMIT_CHANGE_ 各 4（REQUESTED/APPLIED/APPLY_FAILED/CANCELLED）+ '
    + 'CUSTOMER_TAG_ASSIGNED/CUSTOMER_TAG_REVOKED + TRANSACTION_LIMIT_REJECTED（非本批裸名，顺带补登），得 89；'
    + '+ 10 Task15(2026-09-02) 托管钱包创建 + 提现地址登记两族：CUSTODIAN_WALLET_CREATE_REQUESTED/'
    + 'CREATED/FAILED/CANCELLED 四码 + WITHDRAWAL_ADDRESS_REGISTERED/ACTIVATED/CANCELLED/'
    + 'SUSPENDED/DEACTIVATED/COOLING_SKIPPED 六码，得 99；'
    + '+ 2 Task15 收尾(2026-09-02) 常规登录 MFA 二次校验：MFA_LOGIN_VERIFIED/MFA_LOGIN_VERIFY_FAILED'
    + '（体检漏数的第 14 族裸词，码值不变，从旧附册迁入合同），得 101；'
    + '− 6 波一(2026-09-04)T2：资产创建+激活两族（ASSET_CREATED_AND_PROVISIONED/ASSET_CREATION_FAILED/'
    + 'ASSET_PROVISIONING_UPDATED/ASSET_ACTIVATION_REQUESTED/ASSET_ACTIVATED/ASSET_ACTIVATION_FAILED）'
    + '随上架/激活整条路退役迁出（业主定「本轮不做新资产上线」），剩 SUSPENSION_/REACTIVATION_ 两族六码，得 95；'
    + '− 5 波一(2026-09-04)T4：托管钱包创建四码（CUSTODIAN_WALLET_CREATE_REQUESTED/CREATED/FAILED/'
    + 'CANCELLED）+ WALLET_STATUS_UPDATED 随托管钱包创建整条路 + 钱包状态开关退役迁出（平台钱包只从'
    + '种子来、管理台只读），得 90；'
    + '+ 2 波一(2026-09-04)T8：提现地址簿改按网络归属，补两个新动作——WITHDRAWAL_ADDRESS_UPDATED'
    + '（客户改标签/收款人）/WITHDRAWAL_ADDRESS_UNSUSPENDED（管理员恢复，补 D5 出边），得 92；'
    + '− 4 波一(2026-09-04)T10：限额只改不建不删——创建流四码（TRANSACTION_LIMIT_CREATION_REQUESTED/'
    + 'APPLIED/APPLY_FAILED/CANCELLED）随创建流整条退役迁出，得 88；'
    + '+ 6 波一(2026-09-04)T11：费率两族新增「退役等级」动作——SWAP_FEE_LEVEL_RETIRE_REQUESTED/'
    + 'SWAP_FEE_LEVEL_RETIRED/SWAP_FEE_LEVEL_RETIRE_CANCELLED + WITHDRAWAL 同型三码，得 94；'
    + '+ 7 波一(2026-09-04)T14：种子身世七码——ASSET_SEEDED/CUSTODIAN_WALLET_SEEDED/'
    + 'TRANSACTION_LIMIT_SEEDED/SWAP_FEE_LEVEL_SEEDED/WITHDRAWAL_FEE_LEVEL_SEEDED/'
    + 'CUSTOMER_DEPOSIT_ADDRESS_SEEDED/WITHDRAWAL_ADDRESS_SEEDED（配置随版本装载，装载即留痕），得 101）', () => {
    expect(codes).toHaveLength(101);
  });

  it('全部全局唯一（键即字面量，无重复）', () => {
    expect(new Set(codes).size).toBe(codes.length);
  });

  it('六个后缀语义封闭，无例外', () => {
    // 站7 收编追加：MISSING/CREATED/UPDATED/RECORDED/EFFECTIVE/REVOKED/ADVANCED（现名保守，收编不改名）
    // SIMULATED：ADMIN_ACCESS_DENIED 之外另一处历史遗漏（APPROVAL_TIMEOUT_SIMULATED，此前未同步本断言）
    // APPLY_FAILED：Task12(2026-09-01) 费率两域专设失败码——不复用「APPLIED + outcome=FAILED」老套路
    // FAILED：Task13(2026-09-01) 资产四族——ASSET_CREATION_FAILED/ASSET_ACTIVATION_FAILED/
    // ASSET_SUSPENSION_FAILED/ASSET_REACTIVATION_FAILED 四码新增裸 FAILED 后缀
    // PROVISIONED/ACTIVATED/SUSPENDED/REACTIVATED：Task13 六个码值不变只进合同的一部分——
    // ASSET_CREATED_AND_PROVISIONED/ASSET_ACTIVATED/ASSET_SUSPENDED/ASSET_REACTIVATED
    // 沿用旧附册里的历史值（现名保守，入册不改名）
    // ASSIGNED：Task14(2026-09-02) CUSTOMER_TAG_ASSIGNED 新增裸 ASSIGNED 后缀
    // REJECTED：Task14 TRANSACTION_LIMIT_REJECTED（沿用旧附册历史值，入册不改名）
    // REGISTERED：Task15(2026-09-02) WITHDRAWAL_ADDRESS_REGISTERED 新增裸 REGISTERED 后缀
    // DEACTIVATED：Task15 WITHDRAWAL_ADDRESS_DEACTIVATED 新增裸 DEACTIVATED 后缀
    // SKIPPED：Task15 WITHDRAWAL_ADDRESS_COOLING_SKIPPED（MANUAL_COOLING_SKIP 改名）新增裸 SKIPPED 后缀
    // VERIFIED：Task15 收尾(2026-09-02) MFA_LOGIN_VERIFIED 新增裸 VERIFIED 后缀（沿用旧附册历史值，
    // 入册不改名；MFA_LOGIN_VERIFY_FAILED 已含在既有 FAILED 后缀里，不必新增）
    // UNSUSPENDED：波一(2026-09-04)T8 WITHDRAWAL_ADDRESS_UNSUSPENDED 新增裸 UNSUSPENDED 后缀
    // （UPDATED 后缀已在库，WITHDRAWAL_ADDRESS_UPDATED 不需要新增）
    // RETIRED：波一(2026-09-04)T11 SWAP_FEE_LEVEL_RETIRED/WITHDRAWAL_FEE_LEVEL_RETIRED 新增裸 RETIRED
    // 后缀（*_RETIRE_REQUESTED/*_RETIRE_CANCELLED 已含在既有 REQUESTED/CANCELLED 后缀里，不必新增）
    // SEEDED：波一(2026-09-04)T14 种子身世七码新增裸 SEEDED 后缀（配置随版本装载，装载即留痕）
    const ok = /_(REQUESTED|APPLIED|COMPLETED|CANCELLED|EXPIRED|DENIED|GRANTED|SUBMITTED|DECLINED|DISPATCHED|ACCEPTED|INITIATED|BOUND|CONFIRMED|ISSUED|GENERATED|DOWNLOADED|QUERIED|RELEASED|MISSING|CREATED|UPDATED|RECORDED|EFFECTIVE|REVOKED|ADVANCED|SIMULATED|APPLY_FAILED|FAILED|PROVISIONED|ACTIVATED|SUSPENDED|REACTIVATED|ASSIGNED|REJECTED|REGISTERED|DEACTIVATED|SKIPPED|VERIFIED|UNSUSPENDED|RETIRED|SEEDED)$/;
    const bad = codes.filter((c) => !ok.test(c));
    expect(bad).toEqual([]);
  });

  it('每码都声明了四件事', () => {
    for (const c of codes) {
      const s = V1_AUDIT_ACTIONS[c];
      expect(typeof s.domain).toBe('string');
      expect(Object.values(AuditCorrelationMode)).toContain(s.correlationMode);
      expect(Array.isArray(s.requiredFields)).toBe(true);
      expect(typeof s.requiresCausation).toBe('boolean');
    }
  });

  it('前缀优先：同一趟流程的码共享前缀', () => {
    const expectCount: Record<string, number> = {
      'ADMIN_INVITE_': 5, 'ADMIN_FIRST_LOGIN_': 4, 'ADMIN_ROLE_CHANGE_': 3,
      'ADMIN_SUSPENSION_': 2, 'ADMIN_REACTIVATION_': 2, 'ADMIN_PASSWORD_RESET_': 6,
      'ADMIN_MFA_RESET_': 3, 'ADMIN_ACCOUNT_LOCK_': 2,
      'ROLE_DEFINITION_CREATE_': 3, 'ROLE_DEFINITION_MODIFY_': 3,
      'APPROVAL_POLICY_CHANGE_': 2, 'AUDIT_EVIDENCE_EXPORT_': 3,
      // Task12(2026-09-01)：费率两域裸名换前缀唯一新码，四族各 4 码
      'SWAP_FEE_LEVEL_CREATION_': 4, 'SWAP_FEE_LEVEL_CHANGE_': 4,
      'WITHDRAWAL_FEE_LEVEL_CREATION_': 4, 'WITHDRAWAL_FEE_LEVEL_CHANGE_': 4,
      // 波一(2026-09-04)T11：退役等级各族 REQUESTED+CANCELLED 共享前缀 2 码；RETIRED 是
      // 不规则过去式（同 ASSET_SUSPENDED/ASSET_REACTIVATED 判例），不进前缀桶。
      'SWAP_FEE_LEVEL_RETIRE_': 2, 'WITHDRAWAL_FEE_LEVEL_RETIRE_': 2,
      // Task13(2026-09-01) 资产四族 → 波一(2026-09-04)T2 收窄：创建/激活两族（ASSET_CREATION_/
      // ASSET_ACTIVATION_ 前缀）随上架/激活整条路退役一并迁出；SUSPENSION_/REACTIVATION_
      // 两族原样保留，REQUESTED/FAILED 仍共享前缀各 2 码，ASSET_SUSPENDED/ASSET_REACTIVATED
      // 是保留原值的不规则过去式，不进前缀桶（同 WALLET_STATUS_UPDATED 等单码一样落单）。
      'ASSET_SUSPENSION_': 2, 'ASSET_REACTIVATION_': 2,
      // Task14(2026-09-02)：限额两族裸名换前缀唯一新码，各 4 码 → 波一(2026-09-04)T10：
      // CREATION_ 随创建流整条退役迁出（限额只改不建不删）；断言 0 而不是删掉这一行，同
      // REGULATORY_GATE_ 判例，钉住「live 表里该前缀一个都没有」。CHANGE_ 原样保留仍 4 码。
      // TRANSACTION_LIMIT_REJECTED 不进任何前缀桶（单码落单，同 WALLET_STATUS_UPDATED）。
      'TRANSACTION_LIMIT_CREATION_': 0, 'TRANSACTION_LIMIT_CHANGE_': 4,
      'CUSTOMER_TAG_': 2,
      // Task15(2026-09-02) CUSTODIAN_WALLET_CREATE_ 三码 → 波一(2026-09-04)T4 随托管钱包
      // 创建整条路退役一并迁出（不再是活码）。WITHDRAWAL_ADDRESS_ 原六码共享前缀
      // （REGISTERED/ACTIVATED/CANCELLED/SUSPENDED/DEACTIVATED/COOLING_SKIPPED），
      // + 2 波一(2026-09-04)T8：UPDATED/UNSUSPENDED（改标签+管理员恢复两新动作），得 8；
      // + 1 波一(2026-09-04)T14：WITHDRAWAL_ADDRESS_SEEDED（种子身世，提现地址簿随演示
      // 造数装载即留痕），得 9；无不规则过去式例外。
      'WITHDRAWAL_ADDRESS_': 9,
      // Task15 收尾(2026-09-02)：常规登录 MFA 二次校验两码共享前缀（区别于
      // ADMIN_FIRST_LOGIN_——那是首次登录专属四步链，不是同一趟旅程）。
      'MFA_LOGIN_': 2,
      // REGULATORY_GATE_ 曾 7 码，Task 5(2026-08-30) 随监管闸门整块退役。
      // 断言 0 而不是删掉这一行：只有显式钉住「live 表里该前缀一个都没有」，才能挡住
      // 「新铸一个从未出现过的 REGULATORY_GATE_* 码进 live 表、同时别处删一个键把总数
      // 维持在 48」这条绕过路径——它躲得过总数断言，也躲得过退役名册零交集断言。
      'REGULATORY_GATE_': 0,
    };
    for (const [p, n] of Object.entries(expectCount)) {
      expect(codes.filter((c) => c.startsWith(p))).toHaveLength(n);
    }
  });

  it('恰好 26 个 START（13 + Task12 四个 REQUESTED 各起一段新旅程 + Task13 五个：'
    + 'ASSET_CREATED_AND_PROVISIONED/ASSET_CREATION_FAILED 各起创建旅程 + 三族 REQUESTED'
    + ' + Task14 两个：TRANSACTION_LIMIT_CREATION_REQUESTED/TRANSACTION_LIMIT_CHANGE_REQUESTED'
    + '——CUSTOMER_TAG_ASSIGNED/REVOKED 与 TRANSACTION_LIMIT_REJECTED 都是单步动作，无旅程可开，定 NONE'
    + ' + Task15 两个：CUSTODIAN_WALLET_CREATE_REQUESTED/WITHDRAWAL_ADDRESS_REGISTERED 各起一段新旅程'
    + '——其余 8 码都是 INHERIT 读回同一旅程的 correlationId'
    + '（Task15 收尾新增的 MFA_LOGIN_VERIFIED/MFA_LOGIN_VERIFY_FAILED 都是单步登录校验、'
    + '无旅程可开，定 NONE，不贡献 START），得 26；'
    + '− 3 波一(2026-09-04)T2：ASSET_CREATED_AND_PROVISIONED/ASSET_CREATION_FAILED/'
    + 'ASSET_ACTIVATION_REQUESTED 三个 START 随创建/激活两族退役迁出，剩 ASSET_SUSPENSION_REQUESTED/'
    + 'ASSET_REACTIVATION_REQUESTED 两个 START，得 23；'
    + '− 1 波一(2026-09-04)T4：CUSTODIAN_WALLET_CREATE_REQUESTED 随托管钱包创建整条路退役迁出，'
    + '得 22；'
    + '− 1 波一(2026-09-04)T10：TRANSACTION_LIMIT_CREATION_REQUESTED 随创建流整条退役迁出，得 21；'
    + '+ 2 波一(2026-09-04)T11：SWAP_FEE_LEVEL_RETIRE_REQUESTED/WITHDRAWAL_FEE_LEVEL_RETIRE_REQUESTED'
    + ' 各起一段退役旅程，得 23；'
    + '+ 7 波一(2026-09-04)T14：种子身世七码全部定 S——每条装载都是自己旅程的起点，得 30）', () => {
    expect(codes.filter((c) => V1_AUDIT_ACTIONS[c].correlationMode === AuditCorrelationMode.START))
      .toHaveLength(30);
  });

  it('退役码 97 个（V1 域 11 + 充值域 18+1 + 提现域 18 + 兑换域 3 + 对账域 4 + Task5扩面 19：'
    + '监管闸门7+五本档案簿10+LP配置1+手工建户1 + Task13(2026-09-01) 资产四族裸名 6：'
    + 'SUSPENSION_REQUESTED/SUSPENSION_EXECUTION_FAILED/REACTIVATION_REQUESTED/'
    + 'REACTIVATION_EXECUTION_FAILED/ACTIVATION_REQUESTED/ACTIVATION_FAILED'
    + ' + Task14(2026-09-02) 限额/标签共用裸名 9：CREATION_REQUESTED/CREATION_APPLIED/'
    + 'CREATION_APPLY_FAILED/CREATION_CANCELLED/CHANGE_REQUESTED/CHANGE_APPLIED/CHANGE_CANCELLED/'
    + 'TAG_ASSIGNED/TAG_REVOKED（CHANGE_APPLY_FAILED 已在站7批次登记过，不重复计数），得 89'
    + ' + Task15(2026-09-02) 托管钱包+提现地址裸名 10：CREATE_REQUESTED/WALLET_CREATED/'
    + 'WALLET_CREATE_FAILED/CREATE_CANCELLED/ADDRESS_REGISTERED/ADDRESS_ACTIVATED/'
    + 'ADDRESS_CANCELLED/ADDRESS_SUSPENDED/ADDRESS_DEACTIVATED/MANUAL_COOLING_SKIP，得 99'
    + ' − 2 Task15 收尾(2026-09-02)：MFA_LOGIN_VERIFIED/MFA_LOGIN_VERIFY_FAILED 移出——站7首铸'
    + '（9aac76e4）预登记时假设会改名退役，核实后码值不变只是从旧附册搬进 V1_AUDIT_ACTIONS，'
    + '按 TRANSACTION_LIMIT_REJECTED 判例不登退役闸，得 97'
    + ' + 6 波一(2026-09-04)T2：ASSET_CREATED_AND_PROVISIONED/ASSET_CREATION_FAILED/'
    + 'ASSET_PROVISIONING_UPDATED/ASSET_ACTIVATION_REQUESTED/ASSET_ACTIVATED/ASSET_ACTIVATION_FAILED'
    + ' 六码随上架/激活整条路退役新入闸，得 103'
    + ' + 6 波一(2026-09-04)T4：CUSTODIAN_WALLET_CREATE_REQUESTED/CUSTODIAN_WALLET_CREATED/'
    + 'CUSTODIAN_WALLET_CREATE_FAILED/CUSTODIAN_WALLET_CREATE_CANCELLED/WALLET_STATUS_UPDATED/'
    + 'DEPOSIT_WALLET_CREATED 六码随托管钱包创建整条路 + 钱包状态开关 + 客户充值地址供给改名'
    + '新入闸，得 109'
    + ' + 4 波一(2026-09-04)T10：TRANSACTION_LIMIT_CREATION_REQUESTED/APPLIED/APPLY_FAILED/'
    + 'CANCELLED 四码随创建流整条退役新入闸，得 113），'
    + '且与五本在用名册零交集', () => {
    expect(DEPRECATED_AUDIT_ACTIONS).toHaveLength(113);
    expect(DEPRECATED_AUDIT_ACTIONS.filter((d) => codes.includes(d))).toEqual([]);
    expect(DEPRECATED_AUDIT_ACTIONS.filter((d) => d in V4_DEPOSIT_AUDIT_ACTIONS)).toEqual([]);
    expect(DEPRECATED_AUDIT_ACTIONS.filter((d) => d in V5_WITHDRAW_AUDIT_ACTIONS)).toEqual([]);
    expect(DEPRECATED_AUDIT_ACTIONS.filter((d) => d in V6_SWAP_AUDIT_ACTIONS)).toEqual([]);
    expect(DEPRECATED_AUDIT_ACTIONS.filter((d) => d in V8_RECON_AUDIT_ACTIONS)).toEqual([]);
  });
});
