export const AuditModules = {
  AUDIT_LOGS: 'audit-logging',
  GOVERNANCE_APPROVALS: 'governance/approvals',
  GOVERNANCE_REGISTRIES: 'governance/registries',
  GOVERNANCE_REGULATORY_GATES: 'governance/regulatory-gates',
  RISK_DECISION_RECORDS: 'risk-engine/risk-decision-records',
  AUTH: 'identity/auth',
  ACCESS_CONTROL: 'identity/access-control',
  CUSTOMER_AUTH: 'identity/auth/customer',
  ONBOARDING: 'identity/onboarding',
  PAYINS: 'asset-treasury/payins',
  DEPOSIT_TRANSACTIONS: 'trading/deposit-transactions',
  SWAP_TRANSACTIONS: 'trading/swap-transactions',
  SWAP_QUOTES: 'trading/swap-quotes',
  PRICING_CENTER: 'trading/pricing-center',
  WITHDRAW_TRANSACTIONS: 'trading/withdraw-transactions',
  PAYOUTS: 'asset-treasury/payouts',
  SAFEGUARDING_RECONCILIATION: 'clearing-settle/safeguarding-reconciliation',
  INTERNAL_TRANSACTIONS: 'asset-treasury/internal-transactions',
  INTERNAL_FUNDS: 'asset-treasury/internal-funds',
  TRANSACTION_COMPLIANCE: 'risk-engine/transaction-compliance',
  ASSETS: 'asset-treasury/assets',
  LIQUIDITY_CONFIG: 'counterparty/liquidity-config',
  ACCT_EVENTS: 'accounting/acct-events',
  CLEARING_TEMPLATES: 'clearing-settle/clearing-templates',
  JOURNAL_HEADER_TEMPLATES: 'accounting/journal-header-templates',
  JOURNAL_LINE_TEMPLATES: 'accounting/journal-line-templates',
  CUSTOMER_SWAP_RATES: 'identity/customer-swap-rates',
  COA: 'accounting/coa',
  WALLETS: 'asset-treasury/wallets',
  CUSTOMERS: 'identity/customers',
  INBOUND_TRANSFER_SIGNALS: 'trading/inbound-transfer-signals',
  WITHDRAW_WORKFLOW: 'orchestrators/withdraw-workflow',
} as const;

export const AuditEntityTypes = {
  APPROVAL_CASE: 'APPROVAL_CASE',
  SHAREHOLDING_REGISTRY_VERSION: 'SHAREHOLDING_REGISTRY_VERSION',
  APPOINTMENT_RECORD: 'APPOINTMENT_RECORD',
  REGULATORY_GATE_ITEM: 'REGULATORY_GATE_ITEM',
  TRAINING_RECORD: 'TRAINING_RECORD',
  CONFLICT_DISCLOSURE: 'CONFLICT_DISCLOSURE',
  WIND_DOWN_MATERIAL: 'WIND_DOWN_MATERIAL',
  ONBOARDING: 'ONBOARDING',
  ACCESS_CONTROL: 'ACCESS_CONTROL',
  ADMIN_ROLE_CHANGE_REQUEST: 'ADMIN_ROLE_CHANGE_REQUEST',
  RISK_DECISION_RECORD: 'RISK_DECISION_RECORD',
  PAYIN: 'PAYIN',
  DEPOSIT_TRANSACTION: 'DEPOSIT_TRANSACTION',
  SWAP_TRANSACTION: 'SWAP_TRANSACTION',
  WITHDRAW_TRANSACTION: 'WITHDRAW_TRANSACTION',
  PAYOUT: 'PAYOUT',
  RECONCILIATION_BREAK: 'RECONCILIATION_BREAK',
  RECONCILIATION_WARNING: 'RECONCILIATION_WARNING',
  SAFEGUARDING_RUN: 'SAFEGUARDING_RUN',
  FIAT_STATEMENT_IMPORT: 'FIAT_STATEMENT_IMPORT',
  INTERNAL_TRANSACTION: 'INTERNAL_TRANSACTION',
  INTERNAL_FUND: 'INTERNAL_FUND',
  AUDIT_EVIDENCE_PACKAGE: 'AUDIT_EVIDENCE_PACKAGE',
  KYT_CASE: 'KYT_CASE',
  TRAVEL_RULE_CASE: 'TRAVEL_RULE_CASE',
  AUTH: 'AUTH',
  CONFIG: 'CONFIG',
  ASSET: 'ASSET',
  LIQUIDITY_CONFIG: 'LIQUIDITY_CONFIG',
  ACCT_EVENT: 'ACCT_EVENT',
  CLEARING_TEMPLATE: 'CLEARING_TEMPLATE',
  JOURNAL_HEADER_TEMPLATE: 'JOURNAL_HEADER_TEMPLATE',
  JOURNAL_LINE_TEMPLATE: 'JOURNAL_LINE_TEMPLATE',
  CUSTOMER_SWAP_RATE: 'CUSTOMER_SWAP_RATE',
  COA: 'COA',
  WALLET: 'WALLET',
  WITHDRAWAL_ADDRESS: 'WITHDRAWAL_ADDRESS',
  CUSTOMER: 'CUSTOMER',
  INBOUND_TRANSFER_SIGNAL: 'INBOUND_TRANSFER_SIGNAL',
  SWAP_QUOTE: 'SWAP_QUOTE',
  PRICING_POLICY: 'PRICING_POLICY',
  WITHDRAW_PRICING_QUOTE: 'WITHDRAW_PRICING_QUOTE',
  ADMIN_USER: 'ADMIN_USER',
  PASSWORD_RESET_TOKEN: 'PASSWORD_RESET_TOKEN',
  APPROVAL_POLICY: 'APPROVAL_POLICY',
  TB_ACCOUNT: 'TB_ACCOUNT',
  TRANSACTION_LIMIT_POLICY: 'TRANSACTION_LIMIT_POLICY',
  WITHDRAWAL_FEE_LEVEL: 'WITHDRAWAL_FEE_LEVEL',
  WITHDRAWAL_FEE_LEVEL_CHANGE_REQUEST: 'WITHDRAWAL_FEE_LEVEL_CHANGE_REQUEST',
  SWAP_FEE_LEVEL: 'SWAP_FEE_LEVEL',
  SWAP_FEE_LEVEL_CHANGE_REQUEST: 'SWAP_FEE_LEVEL_CHANGE_REQUEST',
  INTERNAL_TRANSFER: 'INTERNAL_TRANSFER',
  SETTLEMENT_BATCH: 'SETTLEMENT_BATCH',
  OUTSTANDING: 'OUTSTANDING',
  FEE_ACCRUAL: 'FEE_ACCRUAL',
  RECONCILIATION_RUN_V8: 'RECONCILIATION_RUN_V8',
  RECONCILIATION_CASE: 'RECONCILIATION_CASE',
  RECONCILIATION_LINE_ITEM: 'RECONCILIATION_LINE_ITEM',
  CUSTOMER_TAG: 'CUSTOMER_TAG',
  MATERIAL_REQUEST: 'MATERIAL_REQUEST',
} as const;

export const AuditWorkflowTypes = {
  // Trading workflows
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  SWAP: 'SWAP',
  TRANSACTION: 'TRANSACTION',
  // Onboarding / compliance
  ONBOARDING: 'ONBOARDING',
  PERIODIC_REVIEW: 'PERIODIC_REVIEW',
  // Governance
  APPROVAL: 'APPROVAL',
  GOVERNANCE_REGISTRY: 'GOVERNANCE_REGISTRY',
  REGULATORY_GATE: 'REGULATORY_GATE',
  // Clearing & settlement
  SETTLEMENT: 'SETTLEMENT',
} as const;

export const AuditBusinessWorkflowTypes = {
  ADMIN_LOGIN_ACCESS: 'ADMIN_LOGIN_ACCESS',
  ADMIN_ROLE_BINDING_CHANGE: 'ADMIN_ROLE_BINDING_CHANGE',
  AUDIT_EVIDENCE_EXPORT: 'AUDIT_EVIDENCE_EXPORT',
  // Governance redesign workflow types (C1–D2)
  ADMIN_INVITE: 'ADMIN_INVITE',
  ADMIN_SUSPENSION: 'ADMIN_SUSPENSION',
  ADMIN_REACTIVATION: 'ADMIN_REACTIVATION',
  ADMIN_FIRST_LOGIN: 'ADMIN_FIRST_LOGIN',
  APPROVAL_POLICY: 'APPROVAL_POLICY',
  // Role Definition Governance (2026-05-08)
  ROLE_DEFINITION_CREATE: 'ROLE_DEFINITION_CREATE',
  ROLE_DEFINITION_MODIFY: 'ROLE_DEFINITION_MODIFY',
  // Credential Reset Governance (2026-05-10)
  ADMIN_PASSWORD_RESET: 'ADMIN_PASSWORD_RESET',
  ADMIN_MFA_RESET: 'ADMIN_MFA_RESET',
  // Custodian Wallet Create (2026-05-13)
  CUSTODIAN_WALLET_CREATE: 'CUSTODIAN_WALLET_CREATE',
  WITHDRAWAL_ADDRESS_REGISTRATION: 'WITHDRAWAL_ADDRESS_REGISTRATION',
  TB_ACCOUNT_MANUAL_CREATE: 'TB_ACCOUNT_MANUAL_CREATE',
  // Asset Suspension (2026-05-14)
  ASSET_SUSPENSION: 'ASSET_SUSPENSION',
  ASSET_REACTIVATION: 'ASSET_REACTIVATION',
  // Asset Creation & Activation (2026-05-14)
  ASSET_CREATION: 'ASSET_CREATION',
  ASSET_ACTIVATION: 'ASSET_ACTIVATION',
  // Transaction Limit Change (2026-05-16)
  TRANSACTION_LIMIT_CHANGE: 'TRANSACTION_LIMIT_CHANGE',
  // Transaction Limit Creation (2026-05-16)
  TRANSACTION_LIMIT_CREATION: 'TRANSACTION_LIMIT_CREATION',
  // Transaction Limit Enforcement (2026-07-16) — L1 per-transaction gate rejections (A/B)
  TRANSACTION_LIMIT_ENFORCEMENT: 'TRANSACTION_LIMIT_ENFORCEMENT',
  // Deposit Below-Min Confiscation (2026-07-16) — V1 maker-checker confiscation of below-min deposit as fee
  DEPOSIT_CONFISCATION: 'DEPOSIT_CONFISCATION',
  // Deposit Return/Seize/Unfreeze maker-checker approvals (A2, 计划2) — 复刻 DEPOSIT_CONFISCATION
  DEPOSIT_RETURN: 'DEPOSIT_RETURN',
  DEPOSIT_SEIZE: 'DEPOSIT_SEIZE',
  DEPOSIT_UNFREEZE: 'DEPOSIT_UNFREEZE',
  // Withdraw FROZEN Unfreeze/Sanction-Refund maker-checker approvals (Task 8, 2026-08-03) — 复刻 DEPOSIT_UNFREEZE
  WITHDRAW_UNFREEZE: 'WITHDRAW_UNFREEZE',
  WITHDRAW_SANCTION_REFUND: 'WITHDRAW_SANCTION_REFUND',
  // Withdrawal Fee Level (2026-05-30)
  WITHDRAWAL_FEE_LEVEL_CREATION: 'WITHDRAWAL_FEE_LEVEL_CREATION',
  WITHDRAWAL_FEE_LEVEL_CHANGE: 'WITHDRAWAL_FEE_LEVEL_CHANGE',
  // Swap Fee Level (2026-05-31)
  SWAP_FEE_LEVEL_CREATION: 'SWAP_FEE_LEVEL_CREATION',
  SWAP_FEE_LEVEL_CHANGE: 'SWAP_FEE_LEVEL_CHANGE',
  // Trading Tier Upgrade (pre-registered, workflow deferred)
  TRADING_TIER_UPGRADE: 'TRADING_TIER_UPGRADE',
  // Withdraw Large-Value Approval Gate (2026-06-01)
  WITHDRAW_LARGE_VALUE_APPROVAL: 'WITHDRAW_LARGE_VALUE_APPROVAL',
  // Internal Transfer (V7, 2026-06-03)
  INTERNAL_TRANSFER: 'INTERNAL_TRANSFER',
  // V8 Reconciliation (2026-06-18)
  V8_RECONCILIATION: 'clearing-settle/reconciliation',
  // Customer Tags (2026-07-13)
  CUSTOMER_TAG: 'CUSTOMER_TAG',
  // Customer Restriction Release (2026-08-15) — 贴/撕便签的审计都归这条 workflow
  CUSTOMER_RESTRICTION_RELEASE: 'CUSTOMER_RESTRICTION_RELEASE',
  // 材料请求账（2026-08-17）：下发 / 提交 / 裁决 / 作废共用一个 workflowType
  MATERIAL_REQUEST: 'MATERIAL_REQUEST',
} as const;

export const AuditUserActions = {
  REQUEST_CREATED: 'REQUEST_CREATED',
  SUBMITTED: 'SUBMITTED',
  APPROVED_FOR_EXECUTION: 'APPROVED_FOR_EXECUTION',
  EXECUTED: 'EXECUTED',
  INVITATION_ISSUED: 'INVITATION_ISSUED',
  INVITATION_RESENT: 'INVITATION_RESENT',
  ACTIVATED: 'ACTIVATED',
  ACTIVATION_FAILED: 'ACTIVATION_FAILED',
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  ROLE_BINDINGS_UPDATED: 'ROLE_BINDINGS_UPDATED',
  CANCELLED: 'CANCELLED',
  EXPORTED: 'EXPORTED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  DOWNLOADED: 'DOWNLOADED',
} as const;

export const AuditActions = {
  APPROVAL_SUBMITTED: 'APPROVAL_SUBMITTED',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  APPROVAL_CANCELLED: 'APPROVAL_CANCELLED',
  APPROVAL_EXPIRED: 'APPROVAL_EXPIRED',
  APPROVAL_EXECUTED: 'APPROVAL_EXECUTED',
  APPROVAL_EXECUTION_FAILED: 'APPROVAL_EXECUTION_FAILED',
  APPROVAL_REQUIRED_MISSING: 'APPROVAL_REQUIRED_MISSING',
  SHAREHOLDING_REGISTRY_CREATED: 'SHAREHOLDING_REGISTRY_CREATED',
  SHAREHOLDING_REGISTRY_UPDATED: 'SHAREHOLDING_REGISTRY_UPDATED',
  APPOINTMENT_RECORD_CREATED: 'APPOINTMENT_RECORD_CREATED',
  APPOINTMENT_RECORD_UPDATED: 'APPOINTMENT_RECORD_UPDATED',
  REGULATORY_GATE_CREATED: 'REGULATORY_GATE_CREATED',
  REGULATORY_GATE_UPDATED: 'REGULATORY_GATE_UPDATED',
  REGULATORY_GATE_SUBMITTED: 'REGULATORY_GATE_SUBMITTED',
  REGULATORY_GATE_FEEDBACK_RECORDED: 'REGULATORY_GATE_FEEDBACK_RECORDED',
  REGULATORY_GATE_RECEIPT_BOUND: 'REGULATORY_GATE_RECEIPT_BOUND',
  REGULATORY_GATE_MARKED_EFFECTIVE: 'REGULATORY_GATE_MARKED_EFFECTIVE',
  REGULATORY_GATE_REVOKED: 'REGULATORY_GATE_REVOKED',
  TRAINING_RECORD_CREATED: 'TRAINING_RECORD_CREATED',
  TRAINING_RECORD_UPDATED: 'TRAINING_RECORD_UPDATED',
  CONFLICT_DISCLOSURE_CREATED: 'CONFLICT_DISCLOSURE_CREATED',
  CONFLICT_DISCLOSURE_UPDATED: 'CONFLICT_DISCLOSURE_UPDATED',
  WIND_DOWN_MATERIAL_CREATED: 'WIND_DOWN_MATERIAL_CREATED',
  WIND_DOWN_MATERIAL_UPDATED: 'WIND_DOWN_MATERIAL_UPDATED',
  DEPOSIT_CREATED: 'DEPOSIT_CREATED',
  DEPOSIT_COMPLIANCE_STARTED: 'DEPOSIT_COMPLIANCE_STARTED',
  DEPOSIT_GATE0_PASSED: 'DEPOSIT_GATE0_PASSED',
  // Sumsub KYT txn submission (Task 8)
  DEPOSIT_SUMSUB_SUBMITTED: 'DEPOSIT_SUMSUB_SUBMITTED',
  DEPOSIT_APPROVED: 'DEPOSIT_APPROVED',
  DEPOSIT_COMPLETED: 'DEPOSIT_COMPLETED',
  DEPOSIT_COMPLIANCE_EVIDENCE_SYNCED: 'DEPOSIT_COMPLIANCE_EVIDENCE_SYNCED',
  DEPOSIT_ACCOUNTING_BLOCKED: 'DEPOSIT_ACCOUNTING_BLOCKED',
  DEPOSIT_HELD_NOT_TRADING_READY: 'DEPOSIT_HELD_NOT_TRADING_READY',
  // Sanctions/MLRO freeze must never be lifted by a late/re-scored "approved" KYT
  // webhook — this is the audit trail for that blocked attempt (fix for the
  // FROZEN→approve→SUCCESS single-operator release hole).
  DEPOSIT_APPROVE_BLOCKED_FROZEN: 'DEPOSIT_APPROVE_BLOCKED_FROZEN',
  // KYT verdict-driven transitions (Sumsub TxnMonitoring, Task 7)
  DEPOSIT_FROZEN: 'DEPOSIT_FROZEN',
  DEPOSIT_MANUAL_CHECKING: 'DEPOSIT_MANUAL_CHECKING',
  // A5(2026-08-13):迟到的 KYT 裁决撞上终态/在途处置态 → 忽略。忽略 ≠ 静默,记一条便于
  // 演示与事后取证("系统收到了、判定不适用、记下来了"),原裁决/存证一个字不动。
  DEPOSIT_KYT_VERDICT_IGNORED: 'DEPOSIT_KYT_VERDICT_IGNORED',
  // 终审必修(2026-08-20):IGNORE 分支撞上迟到的 SANCTION_APPLICANT 裁决 ——
  // 单据状态不该决定"人"要不要被限制(与 swap-workflow.service.ts 的 carve-out
  // 同一条原则)。此时单子本身一步不动(见 DEPOSIT_KYT_VERDICT_IGNORED),但客户
  // 仍被 customerRestrictionsService.open({cause:'SANCTION'}) 摁住 —— 这条审计
  // 承载"虽然单子没动,但人被冻了"这条取证线索。
  DEPOSIT_SANCTION_HIT_ON_IGNORED_VERDICT: 'DEPOSIT_SANCTION_HIT_ON_IGNORED_VERDICT',
  DEPOSIT_MANUAL_APPROVED: 'DEPOSIT_MANUAL_APPROVED',
  DEPOSIT_ONHOLD: 'DEPOSIT_ONHOLD',
  // 已在 ACTION_PENDING 时 Sumsub 又发一个新 applicantActionId(客户交的材料不够,
  // 还要再补)——状态不动,但引用/提交戳/SLA 表刷新(AE-T2)
  // I1 修复:awaitUser 裁决同步之后该单没有任何未提交行(报文整个不带
  // applicantActions,或撤回的恰好是全部未提交行)——拒绝进入/停留 ACTION_PENDING,
  // 单子保持原状态,留痕供排查上游报文异常
  DEPOSIT_AWAITUSER_EMPTY_ACTIONS: 'DEPOSIT_AWAITUSER_EMPTY_ACTIONS',
  // onHold/ACTION_PENDING SLA breach timer (Task 10)
  DEPOSIT_SLA_BREACHED: 'DEPOSIT_SLA_BREACHED',
  // Task 6 (SLA 批次)：管理台「模拟超时」按钮 —— 把 slaDeadline 拨到过去，
  // 下次扫描立即破线。operator 触发、改了持久字段，走 recordByActor。
  DEPOSIT_SLA_TIMEOUT_SIMULATED: 'DEPOSIT_SLA_TIMEOUT_SIMULATED',
  DEPOSIT_HELD_BELOW_MIN: 'DEPOSIT_HELD_BELOW_MIN',   // L1 金额下限挂起(不自动放行)
  DEPOSIT_LIMIT_WAIVED: 'DEPOSIT_LIMIT_WAIVED',       // 运营豁免 below-min(PASS) — used by D5
  DEPOSIT_CONFISCATION_REQUESTED: 'DEPOSIT_CONFISCATION_REQUESTED', // 没收审批发起(maker) — used by D6
  DEPOSIT_CONFISCATION_STARTED: 'DEPOSIT_CONFISCATION_STARTED',     // 没收在途开始(pending+CONFISCATING) — used by C2
  DEPOSIT_CONFISCATION_EXECUTED: 'DEPOSIT_CONFISCATION_EXECUTED',   // 没收落地成功 — used by D7
  DEPOSIT_CONFISCATION_FAILED: 'DEPOSIT_CONFISCATION_FAILED',       // 没收落地失败 — used by D7
  // A1(2026-08-13):没收腿 FAILED/TIMEOUT — 解锁两笔 pending 后退回 OPERATION_PENDING,
  // 运营可重新发起没收。此前这条信号掉地上(handler 只认 CONFIRMED),单子永停 CONFISCATING。
  // ⚠️ A3(2026-08-22)后不再被写入:没收腿改重试三级梯,失败落 RETRIED / STUCK 两条。
  //    常量本身保留(本批不做审计专项,死常量清理留给审计那一轮,见 BACKLOG)。
  // A1:解锁失败(TB 不可达等)。此时 deposit 仍停 CONFISCATING、pending 锁还在,需人工介入。
  DEPOSIT_CONFISCATION_UNLOCK_FAILED: 'DEPOSIT_CONFISCATION_UNLOCK_FAILED',
  // A3(2026-08-22):没收腿重试三级梯 —— 与 DEPOSIT_RETURN_* / DEPOSIT_SEIZE_* 同构。
  DEPOSIT_CONFISCATION_RETRIED: 'DEPOSIT_CONFISCATION_RETRIED',
  DEPOSIT_CONFISCATION_STUCK: 'DEPOSIT_CONFISCATION_STUCK',
  // 退回(RETURNING→RETURNED)地基常量(A1),记账/审批接线见 A2-A4
  DEPOSIT_RETURN_APPROVAL_REQUESTED: 'DEPOSIT_RETURN_APPROVAL_REQUESTED',
  DEPOSIT_RETURN_STARTED: 'DEPOSIT_RETURN_STARTED',
  DEPOSIT_RETURNED: 'DEPOSIT_RETURNED',
  DEPOSIT_RETURN_RETRIED: 'DEPOSIT_RETURN_RETRIED',
  DEPOSIT_RETURN_STUCK: 'DEPOSIT_RETURN_STUCK',
  // 上缴(SEIZING→SEIZED)地基常量(A1),记账/审批接线见 A2-A4
  DEPOSIT_SEIZE_APPROVAL_REQUESTED: 'DEPOSIT_SEIZE_APPROVAL_REQUESTED',
  DEPOSIT_SEIZE_STARTED: 'DEPOSIT_SEIZE_STARTED',
  DEPOSIT_SEIZED: 'DEPOSIT_SEIZED',
  DEPOSIT_SEIZE_RETRIED: 'DEPOSIT_SEIZE_RETRIED',
  DEPOSIT_SEIZE_STUCK: 'DEPOSIT_SEIZE_STUCK',
  // 处置腿（没收/退回/上缴）结算已完成（记账 POSTED + 充值单进终态），但资金单未能
  // 收口到 CLEARED。属视图不一致、非账不平——记一条便于运营发现并手工推单。
  DEPOSIT_LEG_CLEAR_FAILED: 'DEPOSIT_LEG_CLEAR_FAILED',
  // 解冻地基常量(A1),接线见 A5
  DEPOSIT_UNFREEZE_APPROVAL_REQUESTED: 'DEPOSIT_UNFREEZE_APPROVAL_REQUESTED',
  DEPOSIT_UNFROZEN: 'DEPOSIT_UNFROZEN',
  // 客户提交补料材料(AE-T4)——SLA 表由"等客户"切到"等 Provider 重评"
  DEPOSIT_ACTION_SUBMITTED: 'DEPOSIT_ACTION_SUBMITTED',
  // Demo scenario runner (Task 6, 计划1·甲方案) — feeds a deposit through a Sumsub mock
  // scenario fixture (SUMSUB_MOCK_MODE only; endpoint doesn't exist otherwise)
  DEPOSIT_DEMO_SCENARIO_RUN: 'DEPOSIT_DEMO_SCENARIO_RUN',
  CDD_SUBMITTED: 'CDD_SUBMITTED',
  CDD_APPROVED: 'CDD_APPROVED',
  EDD_REJECTED: 'EDD_REJECTED',
  FINAL_APPROVED: 'FINAL_APPROVED',
  CDD_SESSION_CREATED: 'CDD_SESSION_CREATED',
  CDD_SESSION_COMPLETED: 'CDD_SESSION_COMPLETED',
  EDD_SESSION_CREATED: 'EDD_SESSION_CREATED',
  EDD_SESSION_COMPLETED: 'EDD_SESSION_COMPLETED',
  ONBOARDING_WORKFLOW_CLEAR: 'ONBOARDING_WORKFLOW_CLEAR',
  ONBOARDING_WORKFLOW_REJECT: 'ONBOARDING_WORKFLOW_REJECT',
  ONBOARDING_WORKFLOW_REQUIRE_EDD: 'ONBOARDING_WORKFLOW_REQUIRE_EDD',
  PERIODIC_REVIEW_CYCLE_CREATED: 'PERIODIC_REVIEW_CYCLE_CREATED',
  PERIODIC_REVIEW_CDD_SUBMITTED: 'PERIODIC_REVIEW_CDD_SUBMITTED',
  PERIODIC_REVIEW_EDD_SUBMITTED: 'PERIODIC_REVIEW_EDD_SUBMITTED',
  PERIODIC_REVIEW_WORKFLOW_CLEAR: 'PERIODIC_REVIEW_WORKFLOW_CLEAR',
  PERIODIC_REVIEW_WORKFLOW_REJECT: 'PERIODIC_REVIEW_WORKFLOW_REJECT',
  PERIODIC_REVIEW_WORKFLOW_REQUIRE_EDD:
    'PERIODIC_REVIEW_WORKFLOW_REQUIRE_EDD',
  FINAL_APPROVAL_SUBMITTED: 'FINAL_APPROVAL_SUBMITTED',
  FINAL_APPROVAL_RESUBMITTED: 'FINAL_APPROVAL_RESUBMITTED',
  FINAL_APPROVAL_APPROVED: 'FINAL_APPROVAL_APPROVED',
  FINAL_APPROVAL_REJECTED: 'FINAL_APPROVAL_REJECTED',
  FINAL_APPROVAL_CANCELLED: 'FINAL_APPROVAL_CANCELLED',
  FINAL_APPROVAL_EXPIRED: 'FINAL_APPROVAL_EXPIRED',
  MANUAL_INVESTOR_CLASS_OVERRIDE: 'MANUAL_INVESTOR_CLASS_OVERRIDE',
  PAYIN_CREATED: 'PAYIN_CREATED',
  INBOUND_SIGNAL_SUBMITTED: 'INBOUND_SIGNAL_SUBMITTED',
  INBOUND_SIGNAL_SCANNED: 'INBOUND_SIGNAL_SCANNED',
  INBOUND_SIGNAL_MATCHED: 'INBOUND_SIGNAL_MATCHED',
  INBOUND_SIGNAL_BLOCKED: 'INBOUND_SIGNAL_BLOCKED',
  INBOUND_SIGNAL_FAILED: 'INBOUND_SIGNAL_FAILED',
  PAYIN_PENDING_TO_CONFIRMED: 'PAYIN_PENDING_TO_CONFIRMED',
  DEPOSIT_PAYIN_PENDING_TO_COMPLIANCE_PENDING:
    'DEPOSIT_PAYIN_PENDING_TO_COMPLIANCE_PENDING',
  DEPOSIT_COMPLIANCE_PENDING_TO_SUCCESS: 'DEPOSIT_COMPLIANCE_PENDING_TO_SUCCESS',
  SWAP_QUOTE_CREATED: 'SWAP_QUOTE_CREATED',
  SWAP_CREATED: 'SWAP_CREATED',
  SWAP_KYT_SUBMITTED: 'SWAP_KYT_SUBMITTED',
  SWAP_KYT_SUBMIT_FAILED: 'SWAP_KYT_SUBMIT_FAILED',
  // Task 6: applyKytVerdict state-transition audits (markStatus itself writes
  // no audit record — the convention in swap-workflow.service.ts is callers audit).
  SWAP_KYT_APPROVED: 'SWAP_KYT_APPROVED',
  SWAP_KYT_REJECTED: 'SWAP_KYT_REJECTED',
  // Review Fix 1 (Important): a KYT verdict arriving after the swap already
  // entered PROCESSING (mirrors WITHDRAW_POST_BROADCAST_VERDICT) — evidence
  // recorded, no state-machine action taken.
  SWAP_POST_APPROVAL_VERDICT: 'SWAP_POST_APPROVAL_VERDICT',
  // Task 7: handleRejectDisposition's single audit record — carries the
  // soft/hard (tipping-off) decision so an investigator can tell after the
  // fact whether the customer was informed and why.
  SWAP_KYT_REJECTED_DISPOSED: 'SWAP_KYT_REJECTED_DISPOSED',
  // 2026-08-20 制裁分主体：兑换单被冻（客户本人命中制裁 / 跨域冻人广播）。
  // 对齐 DEPOSIT_FROZEN(:240) / WITHDRAW_FROZEN(:427)。
  // ⚠️ 只加这一个 —— 充值/提现的 *_UNFROZEN / *_APPROVE_BLOCKED_FROZEN 那几个
  // 是给「FROZEN 有出边」的域用的，兑换 FROZEN 零出边，抄过来就是死常量。
  SWAP_FROZEN: 'SWAP_FROZEN',
  // 第一批 (2026-08-19)：终态忽略分支（applyKytVerdict 的 no-op 兜底，carve-out
  // 之后）补的审计——忽略 ≠ 静默，与充值/提现域镜像。
  SWAP_KYT_VERDICT_IGNORED: 'SWAP_KYT_VERDICT_IGNORED',
  // Review Fix 1 (Important): handleRejectDisposition itself threw (SQLite
  // lock, transient DB error, etc.) — written before rethrowing so the
  // failure is visible in the audit trail even though the ingestion pipeline
  // also records it generically on the SumsubWebhookEvent row.
  SWAP_KYT_REJECTED_DISPOSITION_FAILED: 'SWAP_KYT_REJECTED_DISPOSITION_FAILED',
  // Task 8: SwapSlaService's own audit for a COMPLIANCE_PENDING swap that
  // timed out waiting for a Sumsub verdict (markStatus writes no audit —
  // same convention as the rest of this file). Deliberately NOT paired with
  // a disposition audit — a timeout carries no verdict, so
  // handleRejectDisposition never runs for this path (see swap-sla.service.ts).
  SWAP_SLA_BREACHED: 'SWAP_SLA_BREACHED',
  // Task 6 (SLA 批次)：管理台「模拟超时」按钮 —— 把 slaDeadline 拨到过去，
  // 下次扫描立即破线。operator 触发、改了持久字段，走 recordByActor。
  SWAP_SLA_TIMEOUT_SIMULATED: 'SWAP_SLA_TIMEOUT_SIMULATED',
  SWAP_SUCCEEDED: 'SWAP_SUCCEEDED',
  SWAP_FAILED: 'SWAP_FAILED',
  SWAP_LEG_POSTED: 'SWAP_LEG_POSTED',
  SWAP_LEG_RETRIED: 'SWAP_LEG_RETRIED',
  SWAP_LEG_STUCK: 'SWAP_LEG_STUCK',
  SWAP_LEG_HALTED_BY_RESTRICTION: 'SWAP_LEG_HALTED_BY_RESTRICTION',
  SWAP_LEG_RESUMED: 'SWAP_LEG_RESUMED',
  SWAP_PRODUCT_RESTRICTED: 'SWAP_PRODUCT_RESTRICTED',
  SWAP_BEST_EXECUTION_EVIDENCE_EXPORTED: 'SWAP_BEST_EXECUTION_EVIDENCE_EXPORTED',
  // Task 9: Demo scenario runner — mirrors DEPOSIT_DEMO_SCENARIO_RUN /
  // WITHDRAW_DEMO_SCENARIO_RUN. Feeds one simulated Sumsub verdict webhook
  // into a swap via the real ingestion pipeline (SUMSUB_MOCK_MODE only).
  SWAP_DEMO_SCENARIO_RUN: 'SWAP_DEMO_SCENARIO_RUN',
  // Task 13: SwapApplicantActionHandler — the exemption loop promised by spec
  // §6 that no earlier task actually built. Consumes applicantActionReviewed
  // for a customer restricted by a prior swap KYT rejection.
  SWAP_ACTION_CLEARED: 'SWAP_ACTION_CLEARED',
  // GREEN arrived for a customer with a sticky hard-line (sanctions) marker —
  // restrictions deliberately held, not lifted. See CustomersService /
  // handleRejectDisposition's hardLineDispositionedAt comments for why this
  // must never be bypassed.
  SWAP_ACTION_GREEN_HARDLINE_HELD: 'SWAP_ACTION_GREEN_HARDLINE_HELD',
  // RED (or any non-GREEN answer) — restrictions stay on, escalated for
  // manual review.
  SWAP_ACTION_ESCALATED: 'SWAP_ACTION_ESCALATED',
  // parity 2026-08-14：客户提交补料材料（客户级会话，mirror DEPOSIT/WITHDRAW_ACTION_SUBMITTED）
  SWAP_ACTION_SUBMITTED: 'SWAP_ACTION_SUBMITTED',
  WITHDRAW_CREATED: 'WITHDRAW_CREATED',
  WITHDRAW_CREATED_TO_PAYOUT_PENDING: 'WITHDRAW_CREATED_TO_PAYOUT_PENDING',
  WITHDRAW_PAYOUT_PENDING_TO_SUCCESS: 'WITHDRAW_PAYOUT_PENDING_TO_SUCCESS',
  PAYOUT_CREATED: 'PAYOUT_CREATED',
  PAYOUT_PENDING_TO_CLEAR: 'PAYOUT_PENDING_TO_CLEAR',
  WITHDRAW_FAILED_REVERSED: 'WITHDRAW_FAILED_REVERSED',
  // V5 Withdrawal Happy Path
  WITHDRAW_REQUESTED: 'WITHDRAW_REQUESTED',
  WITHDRAW_COMPLIANCE_PASSED: 'WITHDRAW_COMPLIANCE_PASSED',
  WITHDRAW_ACCOUNTING_POSTED: 'WITHDRAW_ACCOUNTING_POSTED',
  WITHDRAW_LOCK_RELEASED: 'WITHDRAW_LOCK_RELEASED',
  WITHDRAW_SUCCESS: 'WITHDRAW_SUCCESS',
  // funds_order-driven (Round 2)
  FUNDS_ORDER_ADVANCED: 'FUNDS_ORDER_ADVANCED',
  DEPOSIT_PAYIN_CONFIRMED: 'DEPOSIT_PAYIN_CONFIRMED',
  DEPOSIT_PAYIN_FAILED: 'DEPOSIT_PAYIN_FAILED',
  WITHDRAW_PAYOUT_INITIATED: 'WITHDRAW_PAYOUT_INITIATED',
  WITHDRAW_PAYOUT_CONFIRMED: 'WITHDRAW_PAYOUT_CONFIRMED',
  WITHDRAW_PAYOUT_FAILED: 'WITHDRAW_PAYOUT_FAILED',
  WITHDRAW_APPROVAL_REQUESTED: 'WITHDRAW_APPROVAL_REQUESTED',
  WITHDRAW_APPROVAL_GRANTED: 'WITHDRAW_APPROVAL_GRANTED',
  WITHDRAW_APPROVAL_DECLINED: 'WITHDRAW_APPROVAL_DECLINED',
  // Task 5: Sumsub single-txn submit + applyKytVerdict branches + SLA cron
  WITHDRAW_SUMSUB_SUBMITTED: 'WITHDRAW_SUMSUB_SUBMITTED',
  WITHDRAW_ONHOLD: 'WITHDRAW_ONHOLD',
  // 已在 ACTION_PENDING 时 Sumsub 又发一个新 applicantActionId(客户交的材料不够,
  // 还要再补)——状态不动,但缓存/SLA 表刷新。mirrors DEPOSIT_ACTION_REISSUED。
  WITHDRAW_ACTION_REISSUED: 'WITHDRAW_ACTION_REISSUED',
  // awaitUser 裁决同步之后该单没有任何未提交行(报文整个不带 applicantActions,
  // 或撤回的恰好是全部未提交行)——拒绝进入/停留 ACTION_PENDING,单子保持原状态,
  // 留痕供排查上游报文异常。mirrors DEPOSIT_AWAITUSER_EMPTY_ACTIONS。
  WITHDRAW_AWAITUSER_EMPTY_ACTIONS: 'WITHDRAW_AWAITUSER_EMPTY_ACTIONS',
  WITHDRAW_SLA_BREACHED: 'WITHDRAW_SLA_BREACHED',
  // Task 6 (SLA 批次)：管理台「模拟超时」按钮 —— 把 slaDeadline 拨到过去，
  // 下次扫描立即破线。operator 触发、改了持久字段，走 recordByActor。
  WITHDRAW_SLA_TIMEOUT_SIMULATED: 'WITHDRAW_SLA_TIMEOUT_SIMULATED',
  WITHDRAW_MANUAL_APPROVED: 'WITHDRAW_MANUAL_APPROVED',
  WITHDRAW_FROZEN: 'WITHDRAW_FROZEN',
  WITHDRAW_REFUNDED_BY_TAG: 'WITHDRAW_REFUNDED_BY_TAG',
  // Review Fix 1 (Critical): REJECT_REFUND arriving while FROZEN must not bypass
  // the FROZEN maker-checker — the tag is ignored, this audits the ignored attempt.
  WITHDRAW_REFUND_TAG_ON_FROZEN_IGNORED: 'WITHDRAW_REFUND_TAG_ON_FROZEN_IGNORED',
  // 第一批(2026-08-19):迟到的 KYT 裁决撞上终态/FROZEN → 忽略。忽略 ≠ 静默,记一条
  // 便于演示与事后取证("系统收到了、判定不适用、记下来了"),原裁决/存证一个字不动。
  // mirrors DEPOSIT_KYT_VERDICT_IGNORED。
  WITHDRAW_KYT_VERDICT_IGNORED: 'WITHDRAW_KYT_VERDICT_IGNORED',
  // 终审必修(2026-08-20):IGNORE 分支撞上迟到的 SANCTION_APPLICANT 裁决 ——
  // 单据状态不该决定"人"要不要被限制。mirrors DEPOSIT_SANCTION_HIT_ON_IGNORED_VERDICT。
  WITHDRAW_SANCTION_HIT_ON_IGNORED_VERDICT: 'WITHDRAW_SANCTION_HIT_ON_IGNORED_VERDICT',
  // Review Fix 2 (Important): a KYT verdict arriving after the payout already
  // broadcast (PAYOUT_PENDING) — evidence recorded, no state-machine action.
  WITHDRAW_POST_BROADCAST_VERDICT: 'WITHDRAW_POST_BROADCAST_VERDICT',
  // Task 6: fee-leg order guard + failure three-rung ladder.
  WITHDRAW_FEE_LEG_REBUILT: 'WITHDRAW_FEE_LEG_REBUILT',
  WITHDRAW_FEE_SETTLE_STUCK: 'WITHDRAW_FEE_SETTLE_STUCK',
  // Task 7: admin bounce entry (PAYOUT_PENDING → RETURNED).
  WITHDRAW_BOUNCED: 'WITHDRAW_BOUNCED',
  // Task 8: FROZEN maker-checker gates (initiate side) — mirrors DEPOSIT_UNFREEZE/DEPOSIT_RETURN.
  WITHDRAW_UNFREEZE_APPROVAL_REQUESTED: 'WITHDRAW_UNFREEZE_APPROVAL_REQUESTED',
  WITHDRAW_SANCTION_REFUND_APPROVAL_REQUESTED: 'WITHDRAW_SANCTION_REFUND_APPROVAL_REQUESTED',
  // Task 9: FROZEN maker-checker gates (execution side) — decided-event handlers.
  WITHDRAW_UNFROZEN: 'WITHDRAW_UNFROZEN',
  WITHDRAW_SANCTION_REFUNDED: 'WITHDRAW_SANCTION_REFUNDED',
  // 客户提交补料材料(Task 3, action-embed)——SLA 表由"等客户"切到"等 Provider 重评"。
  // mirrors DEPOSIT_ACTION_SUBMITTED。
  WITHDRAW_ACTION_SUBMITTED: 'WITHDRAW_ACTION_SUBMITTED',
  // Task 10: Demo scenario runner — mirrors DEPOSIT_DEMO_SCENARIO_RUN. Feeds a
  // withdrawal through a Sumsub mock verdict fixture (SUMSUB_MOCK_MODE only —
  // endpoint doesn't exist otherwise).
  WITHDRAW_DEMO_SCENARIO_RUN: 'WITHDRAW_DEMO_SCENARIO_RUN',
  KYT_CASE_CREATED: 'KYT_CASE_CREATED',
  KYT_CASE_UPDATED: 'KYT_CASE_UPDATED',
  TRAVEL_RULE_UPDATED: 'TRAVEL_RULE_UPDATED',
  TX_RISK_EVALUATED: 'TX_RISK_EVALUATED',
  TX_ALERT_UPSERTED: 'TX_ALERT_UPSERTED',
  TX_DEPOSIT_FLAGGED: 'TX_DEPOSIT_FLAGGED',
  TX_DEPOSIT_RELEASED: 'TX_DEPOSIT_RELEASED',
  TX_DEPOSIT_FROZEN: 'TX_DEPOSIT_FROZEN',
  TX_DEPOSIT_REJECTED: 'TX_DEPOSIT_REJECTED',
  TX_DEPOSIT_RELEASE_BLOCKED: 'TX_DEPOSIT_RELEASE_BLOCKED',
  TX_SWAP_FLAGGED: 'TX_SWAP_FLAGGED',
  TX_SWAP_RELEASED: 'TX_SWAP_RELEASED',
  TX_SWAP_REJECTED: 'TX_SWAP_REJECTED',
  TX_SWAP_FAILED: 'TX_SWAP_FAILED',
  TX_WITHDRAW_FLAGGED: 'TX_WITHDRAW_FLAGGED',
  TX_WITHDRAW_RELEASED: 'TX_WITHDRAW_RELEASED',
  TX_WITHDRAW_REJECTED: 'TX_WITHDRAW_REJECTED',
  TX_WITHDRAW_RELEASE_BLOCKED: 'TX_WITHDRAW_RELEASE_BLOCKED',
  TX_WITHDRAW_FINAL_GATE_BLOCKED: 'TX_WITHDRAW_FINAL_GATE_BLOCKED',
  TX_RECONCILIATION_BREAK_DETECTED: 'TX_RECONCILIATION_BREAK_DETECTED',
  TX_RECONCILIATION_BREAK_RESOLVED: 'TX_RECONCILIATION_BREAK_RESOLVED',
  TX_SAFEGUARDING_BREAK_DETECTED: 'TX_SAFEGUARDING_BREAK_DETECTED',
  TX_SAFEGUARDING_BREAK_RESOLVED: 'TX_SAFEGUARDING_BREAK_RESOLVED',
  SAFEGUARDING_RUN_GENERATED: 'SAFEGUARDING_RUN_GENERATED',
  FIAT_STATEMENT_IMPORTED: 'FIAT_STATEMENT_IMPORTED',
  SAFEGUARDING_EVIDENCE_PACKAGE_EXPORTED:
    'SAFEGUARDING_EVIDENCE_PACKAGE_EXPORTED',
  WITHDRAW_EXTREME_VOLATILITY_BLOCKED: 'WITHDRAW_EXTREME_VOLATILITY_BLOCKED',
  RISK_DECISION_MANUAL_SIMULATED: 'MANUAL_RISK_DECISION_SIMULATED',
  ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
  ADMIN_LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
  CUSTOMER_LOGIN_SUCCESS: 'CUSTOMER_LOGIN_SUCCESS',
  CUSTOMER_LOGIN_FAILED: 'CUSTOMER_LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  USER_ROLE_BINDING_UPDATED: 'USER_ROLE_BINDING_UPDATED',
  LP_CONFIG_UPDATED: 'LP_CONFIG_UPDATED',
  ACCT_EVENT_UPDATED: 'ACCT_EVENT_UPDATED',
  CLEARING_TEMPLATE_UPDATED: 'CLEARING_TEMPLATE_UPDATED',
  JOURNAL_TEMPLATE_UPDATED: 'JOURNAL_TEMPLATE_UPDATED',
  COA_CONFIG_UPDATED: 'COA_CONFIG_UPDATED',
  CUSTOMER_SWAP_RATE_UPDATED: 'CUSTOMER_SWAP_RATE_UPDATED',
  PRICING_POLICY_UPDATED: 'PRICING_POLICY_UPDATED',
  SWAP_PRICING_SIMULATED: 'SWAP_PRICING_SIMULATED',
  WITHDRAW_PRICING_SIMULATED: 'WITHDRAW_PRICING_SIMULATED',
  WITHDRAW_PRICING_QUOTE_CREATED: 'WITHDRAW_PRICING_QUOTE_CREATED',
  WITHDRAW_PRICING_QUOTE_CANCELLED: 'WITHDRAW_PRICING_QUOTE_CANCELLED',
  WITHDRAW_PRICING_QUOTE_USED: 'WITHDRAW_PRICING_QUOTE_USED',
  USER_CREATED: 'USER_CREATED',
  ADMIN_INVITATION_CREATED: 'ADMIN_INVITATION_CREATED',
  ADMIN_INVITATION_RESENT: 'ADMIN_INVITATION_RESENT',
  ADMIN_INVITATION_ACCEPTED: 'ADMIN_INVITATION_ACCEPTED',
  ADMIN_INVITATION_ACCEPT_FAILED: 'ADMIN_INVITATION_ACCEPT_FAILED',
  CUSTOMER_REGISTERED: 'CUSTOMER_REGISTERED',
  CUSTOMER_REGISTER_FAILED: 'CUSTOMER_REGISTER_FAILED',
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_FROZEN: 'CUSTOMER_FROZEN',
  CUSTOMER_UNFROZEN: 'CUSTOMER_UNFROZEN',
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',
  // Capability-scoped trading restrictions (2026-08-13) — written by CustomerRestrictionsService
  CUSTOMER_RESTRICTION_ADDED: 'CUSTOMER_RESTRICTION_ADDED',
  CUSTOMER_RESTRICTION_CLEARED: 'CUSTOMER_RESTRICTION_CLEARED',
  WALLET_STATUS_UPDATED: 'WALLET_STATUS_UPDATED',
  DEPOSIT_WALLET_CREATED: 'DEPOSIT_WALLET_CREATED',
  DEPOSIT_WALLET_CREATE_FAILED: 'DEPOSIT_WALLET_CREATE_FAILED',
  SWAP_QUOTE_CANCELLED: 'SWAP_QUOTE_CANCELLED',
  SWAP_QUOTE_USED: 'SWAP_QUOTE_USED',
  SYSTEM_TX_COMPLIANCE_BACKFILL_EXECUTED:
    'SYSTEM_TX_COMPLIANCE_BACKFILL_EXECUTED',
  AUDIT_EVIDENCE_EXPORT_REQUESTED: 'AUDIT_EVIDENCE_EXPORT_REQUESTED',
  AUDIT_EVIDENCE_PACKAGE_EXPORTED: 'AUDIT_EVIDENCE_PACKAGE_EXPORTED',
  AUDIT_EVIDENCE_PACKAGE_DOWNLOADED: 'AUDIT_EVIDENCE_PACKAGE_DOWNLOADED',
  CASE_EVIDENCE_PACKAGE_EXPORTED: 'CASE_EVIDENCE_PACKAGE_EXPORTED',
  ALERT_TRIGGERED: 'ALERT_TRIGGERED',
  ALERT_ACKED: 'ALERT_ACKED',
  ALERT_ASSIGNED: 'ALERT_ASSIGNED',
  ALERT_ESCALATED: 'ALERT_ESCALATED',
  ALERT_OVERDUE_MARKED: 'ALERT_OVERDUE_MARKED',
  ALERT_RESOLVED: 'ALERT_RESOLVED',
  ALERT_FALSE_POSITIVE: 'ALERT_FALSE_POSITIVE',
  ALERT_REOPENED: 'ALERT_REOPENED',
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  INCIDENT_ASSIGNED: 'INCIDENT_ASSIGNED',
  INCIDENT_FROZEN: 'INCIDENT_FROZEN',
  INCIDENT_UNFROZEN: 'INCIDENT_UNFROZEN',
  INCIDENT_RESTRICTED: 'INCIDENT_RESTRICTED',
  INCIDENT_UNRESTRICTED: 'INCIDENT_UNRESTRICTED',
  INCIDENT_REPORTED: 'INCIDENT_REPORTED',
  INCIDENT_OVERDUE_MARKED: 'INCIDENT_OVERDUE_MARKED',
  INCIDENT_INVESTIGATION_STARTED: 'INCIDENT_INVESTIGATION_STARTED',
  INCIDENT_REPORT_DRAFT_SAVED: 'INCIDENT_REPORT_DRAFT_SAVED',
  INCIDENT_REPORT_FINALIZED: 'INCIDENT_REPORT_FINALIZED',
  INCIDENT_SUBMITTED_TO_MLRO: 'INCIDENT_SUBMITTED_TO_MLRO',
  INCIDENT_RETURNED_FOR_INVESTIGATION: 'INCIDENT_RETURNED_FOR_INVESTIGATION',
  INCIDENT_FINAL_DISPOSITION_APPROVED: 'INCIDENT_FINAL_DISPOSITION_APPROVED',
  INCIDENT_FILING_REQUIRED: 'INCIDENT_FILING_REQUIRED',
  INCIDENT_FILING_SUBMITTED: 'INCIDENT_FILING_SUBMITTED',
  INCIDENT_FILING_ACKNOWLEDGED: 'INCIDENT_FILING_ACKNOWLEDGED',
  INCIDENT_FILING_RETURNED: 'INCIDENT_FILING_RETURNED',
  INCIDENT_FILING_CLOSED: 'INCIDENT_FILING_CLOSED',
  INCIDENT_ALERT_LINKED: 'INCIDENT_ALERT_LINKED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  INCIDENT_CLOSED: 'INCIDENT_CLOSED',
  INCIDENT_FALSE_POSITIVE: 'INCIDENT_FALSE_POSITIVE',
  SYSTEM_WITHDRAW_CREATED_ORCHESTRATED: 'SYSTEM_WITHDRAW_CREATED_ORCHESTRATED',
  SYSTEM_WITHDRAW_TERMINAL_ORCHESTRATED: 'SYSTEM_WITHDRAW_TERMINAL_ORCHESTRATED',
  SYSTEM_WITHDRAW_APPROVED_ORCHESTRATED: 'SYSTEM_WITHDRAW_APPROVED_ORCHESTRATED',
  MANUAL_TB_ACCOUNT_CREATED: 'MANUAL_TB_ACCOUNT_CREATED',
  // Internal Transfer (V7, 2026-06-03)
  TRANSFER_WHITELIST_REJECTED: 'TRANSFER_WHITELIST_REJECTED',
  // Settlement Batch
  BATCH_CREATED: 'BATCH_CREATED',
  BATCH_SUCCEEDED: 'BATCH_SUCCEEDED',
  // Generic lifecycle verbs for Outstanding & FeeAccrual (entityType differentiates)
  CREATED: 'CREATED',
  LOCKED: 'LOCKED',
  SETTLED: 'SETTLED',
  // ───── Spec #4: INTERNAL_FUND/INTERNAL_TRANSFER short-name actions (CREATED reused from Spec #3)
  SIGNING: 'SIGNING',
  BROADCASTED: 'BROADCASTED',
  CONFIRMING: 'CONFIRMING',
  CONFIRMED: 'CONFIRMED',
  CLEARED: 'CLEARED',
  FAILED: 'FAILED',
  TIMED_OUT: 'TIMED_OUT',
  CANCELLED: 'CANCELLED',
  REORGED: 'REORGED',
  REQUESTED: 'REQUESTED',
  SUCCEEDED: 'SUCCEEDED',
  // V8 Reconciliation (2026-06-18)
  RECON_RUN_COMPLETED: 'RECON_RUN_COMPLETED',
  RECON_RUN_FAILED: 'RECON_RUN_FAILED',
  RECON_CASE_OPENED: 'RECON_CASE_OPENED',
  RECON_CASE_RECONFIRMED: 'RECON_CASE_RECONFIRMED',
  RECON_INVARIANT_BREAK: 'RECON_INVARIANT_BREAK',
  // Wallet-recon orchestrator Round3 (T5)
  SYSTEM_RECON_RUN_COMPLETED: 'SYSTEM_RECON_RUN_COMPLETED',
  SYSTEM_RECON_CASE_AUTO_HEALED: 'SYSTEM_RECON_CASE_AUTO_HEALED',
  // ── Reconciliation disposition: push-order（平账·推单）──
  RECON_PUSH_ORDER_SYNCED: 'RECON_PUSH_ORDER_SYNCED',
  RECON_PUSH_ORDER_MANUAL: 'RECON_PUSH_ORDER_MANUAL',
  // ── Material Request Ledger（向客户要材料）──
  MATERIAL_REQUEST_ISSUED: 'MATERIAL_REQUEST_ISSUED',
  MATERIAL_REQUEST_SUBMITTED: 'MATERIAL_REQUEST_SUBMITTED',
  MATERIAL_REQUEST_APPROVED: 'MATERIAL_REQUEST_APPROVED',
  MATERIAL_REQUEST_RETRY_REQUESTED: 'MATERIAL_REQUEST_RETRY_REQUESTED',
  MATERIAL_REQUEST_REJECTED: 'MATERIAL_REQUEST_REJECTED',
  MATERIAL_REQUEST_CANCELLED: 'MATERIAL_REQUEST_CANCELLED',
  MATERIAL_REQUEST_ORDER_UNBOUND: 'MATERIAL_REQUEST_ORDER_UNBOUND',
} as const;

export const AuditGovernanceActions = {
  // Admin Login Access
  ADMIN_LOGIN_ACCESS: {
    LOGIN_SUCCESS:    'ADMIN_LOGIN_SUCCESS',
    LOGIN_FAILED:     'ADMIN_LOGIN_FAILED',
    ACCOUNT_LOCKED:   'ACCOUNT_LOCKED',
    ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  },

  // C1 — Admin Invite：已退役，Task 6 迁到 V1_AUDIT_ACTIONS 的
  // ADMIN_INVITE_REQUESTED/DISPATCHED/ACCEPTED/EXPIRED/CANCELLED 五码，全仓零消费方
  // （2026-08-26 grep 核实），本组已删。

  // C2 — Admin Role Binding Change：已退役，Task 6 迁到 V1_AUDIT_ACTIONS 的
  // ADMIN_ROLE_CHANGE_REQUESTED/APPLIED/CANCELLED 三码（新增 CANCELLED），
  // 全仓零消费方，本组已删。

  // C3a — Admin Suspension：已退役，Task 7 迁到 V1_AUDIT_ACTIONS 的
  // ADMIN_SUSPENSION_REQUESTED/APPLIED 两码，全仓零消费方，本组已删。

  // C3b — Admin Reactivation：已退役，Task 7 迁到 V1_AUDIT_ACTIONS 的
  // ADMIN_REACTIVATION_REQUESTED/APPLIED 两码，全仓零消费方，本组已删。

  // C4b — Approval Policy Modification：已退役，Task 8 迁到 V1_AUDIT_ACTIONS 的
  // APPROVAL_POLICY_CHANGE_REQUESTED/APPLIED 两码（不复用 APPROVAL_SUBMITTED——拆条判据乙
  // "PRIMARY 不同必须拆"），全仓零消费方，本组已删。

  // C5 — Audit Evidence Export：已退役，Task 8 迁到 V1_AUDIT_ACTIONS 的
  // AUDIT_EVIDENCE_EXPORT_REQUESTED/GENERATED/DOWNLOADED 三码 + 新增 AUDIT_LOG_QUERIED，
  // 全仓零消费方，本组已删。GENERATION_FAILED 未被收编（见 audit-evidence-export-
  // workflow.service.ts 对应分支注释——payloadDigest 必填，失败时无产物可摘要）。

  // Credential Reset Governance (2026-05-10)：已退役，Task 7 迁到 V1_AUDIT_ACTIONS 的
  // ADMIN_PASSWORD_RESET_SELF_REQUESTED/SELF_TOKEN_ISSUED/SELF_COMPLETED/
  // OFFICER_REQUESTED/OFFICER_APPLIED/CANCELLED 六码，全仓零消费方，本组已删。

  // ADMIN_MFA_RESET：已退役，Task 7 迁到 V1_AUDIT_ACTIONS 的
  // ADMIN_MFA_RESET_REQUESTED/APPLIED/CANCELLED 三码，全仓零消费方，本组已删。

  // C3c — Admin First Login：首登五步（IDENTITY_CONFIRMED/MFA_BINDING_INITIATED/
  // MFA_VERIFY_FAILED/MFA_BINDING_COMPLETED/FIRST_LOGIN_COMPLETED）+ MFA_VERIFY_LOCKED
  // 已退役，Task 6 迁到 V1_AUDIT_ACTIONS 的 ADMIN_FIRST_LOGIN_IDENTITY_CONFIRMED/
  // MFA_INITIATED/MFA_BOUND（收编 FAILED，LOCKED 分支留 TODO 指向 Task 7 的
  // ADMIN_ACCOUNT_LOCK_APPLIED）/COMPLETED 四码。
  // 下面两个 MFA_LOGIN_* 是常规（非首登）登录的 MFA 校验，不在本批 12 码范围内，
  // mfa-binding-workflow.service.ts 的 verifyMfaLogin() 仍在用，原样保留。
  ADMIN_FIRST_LOGIN: {
    MFA_LOGIN_VERIFIED:       'MFA_LOGIN_VERIFIED',
    MFA_LOGIN_VERIFY_FAILED:  'MFA_LOGIN_VERIFY_FAILED',
  },

  // Role Definition Create (2026-05-08)：已退役，Task 8 迁到 V1_AUDIT_ACTIONS 的
  // ROLE_DEFINITION_CREATE_REQUESTED/APPLIED/CANCELLED 三码，全仓零消费方，本组已删。

  // Role Definition Modify (2026-05-08)：已退役，Task 8 迁到 V1_AUDIT_ACTIONS 的
  // ROLE_DEFINITION_MODIFY_REQUESTED/APPLIED/CANCELLED 三码，全仓零消费方，本组已删。

  // Custodian Wallet Create (2026-05-13)
  CUSTODIAN_WALLET_CREATE: {
    CREATE_REQUESTED:      'CREATE_REQUESTED',
    WALLET_CREATED:        'WALLET_CREATED',
    WALLET_CREATE_FAILED:  'WALLET_CREATE_FAILED',
    CREATE_CANCELLED:      'CREATE_CANCELLED',
  },

  // Withdrawal Address Registration (2026-05-13)
  WITHDRAWAL_ADDRESS_REGISTRATION: {
    ADDRESS_REGISTERED:   'ADDRESS_REGISTERED',
    ADDRESS_ACTIVATED:    'ADDRESS_ACTIVATED',
    ADDRESS_CANCELLED:    'ADDRESS_CANCELLED',
    ADDRESS_SUSPENDED:    'ADDRESS_SUSPENDED',
    ADDRESS_DEACTIVATED:  'ADDRESS_DEACTIVATED',
    MANUAL_COOLING_SKIP:  'MANUAL_COOLING_SKIP',
  },

  // Asset Suspension (2026-05-14)
  ASSET_SUSPENSION: {
    SUSPENSION_REQUESTED:          'SUSPENSION_REQUESTED',
    ASSET_SUSPENDED:               'ASSET_SUSPENDED',
    SUSPENSION_EXECUTION_FAILED:   'SUSPENSION_EXECUTION_FAILED',
  },

  // Asset Reactivation (2026-05-14)
  ASSET_REACTIVATION: {
    REACTIVATION_REQUESTED:          'REACTIVATION_REQUESTED',
    ASSET_REACTIVATED:               'ASSET_REACTIVATED',
    REACTIVATION_EXECUTION_FAILED:   'REACTIVATION_EXECUTION_FAILED',
  },

  // Asset Creation (2026-05-14) — no approval, direct create+provision
  ASSET_CREATION: {
    ASSET_CREATED_AND_PROVISIONED: 'ASSET_CREATED_AND_PROVISIONED',
    ASSET_CREATION_FAILED:         'ASSET_CREATION_FAILED',
    ASSET_PROVISIONING_UPDATED:    'ASSET_PROVISIONING_UPDATED',
  },

  // Asset Activation (2026-05-14) — replaces ASSET_LISTING activation
  ASSET_ACTIVATION: {
    ACTIVATION_REQUESTED:  'ACTIVATION_REQUESTED',
    ASSET_ACTIVATED:       'ASSET_ACTIVATED',
    ACTIVATION_FAILED:     'ACTIVATION_FAILED',
  },

  // Transaction Limit Change (2026-05-16)
  TRANSACTION_LIMIT_CHANGE: {
    CHANGE_REQUESTED:      'CHANGE_REQUESTED',
    CHANGE_APPLIED:        'CHANGE_APPLIED',
    CHANGE_APPLY_FAILED:   'CHANGE_APPLY_FAILED',
    CHANGE_CANCELLED:      'CHANGE_CANCELLED',
  },

  // Transaction Limit Creation (2026-05-16)
  TRANSACTION_LIMIT_CREATION: {
    CREATION_REQUESTED:     'CREATION_REQUESTED',
    CREATION_APPLIED:       'CREATION_APPLIED',
    CREATION_APPLY_FAILED:  'CREATION_APPLY_FAILED',
    CREATION_CANCELLED:     'CREATION_CANCELLED',
  },

  // Transaction Limit runtime enforcement (2026-07-16)
  TRANSACTION_LIMIT_REJECTED: 'TRANSACTION_LIMIT_REJECTED',   // L1 金额限额拦截(A/B) — used by Task 4 engine

  // Withdrawal Fee Level Creation (2026-05-30)
  WITHDRAWAL_FEE_LEVEL_CREATION: {
    CREATION_REQUESTED:    'CREATION_REQUESTED',
    CREATION_APPLIED:      'CREATION_APPLIED',
    CREATION_APPLY_FAILED: 'CREATION_APPLY_FAILED',
    CREATION_CANCELLED:    'CREATION_CANCELLED',
  },

  // Withdrawal Fee Level Change (2026-05-30)
  WITHDRAWAL_FEE_LEVEL_CHANGE: {
    CHANGE_REQUESTED:    'CHANGE_REQUESTED',
    CHANGE_APPLIED:      'CHANGE_APPLIED',
    CHANGE_APPLY_FAILED: 'CHANGE_APPLY_FAILED',
    CHANGE_CANCELLED:    'CHANGE_CANCELLED',
  },

  // Swap Fee Level Creation (2026-05-31)
  SWAP_FEE_LEVEL_CREATION: {
    CREATION_REQUESTED:    'CREATION_REQUESTED',
    CREATION_APPLIED:      'CREATION_APPLIED',
    CREATION_APPLY_FAILED: 'CREATION_APPLY_FAILED',
    CREATION_CANCELLED:    'CREATION_CANCELLED',
  },

  // Swap Fee Level Change (2026-05-31)
  SWAP_FEE_LEVEL_CHANGE: {
    CHANGE_REQUESTED:    'CHANGE_REQUESTED',
    CHANGE_APPLIED:      'CHANGE_APPLIED',
    CHANGE_APPLY_FAILED: 'CHANGE_APPLY_FAILED',
    CHANGE_CANCELLED:    'CHANGE_CANCELLED',
  },

  // Customer Tags (2026-07-13)
  CUSTOMER_TAG: {
    TAG_ASSIGNED: 'TAG_ASSIGNED',
    TAG_REVOKED:  'TAG_REVOKED',
  },
} as const;

const AuditRawActionToUserActionMap = {
  [AuditActions.APPROVAL_SUBMITTED]: AuditUserActions.SUBMITTED,
  [AuditActions.APPROVAL_APPROVED]:
    AuditUserActions.APPROVED_FOR_EXECUTION,
  [AuditActions.APPROVAL_EXECUTED]: AuditUserActions.EXECUTED,
  [AuditActions.APPROVAL_EXECUTION_FAILED]: AuditUserActions.EXPORT_FAILED,
  [AuditActions.ADMIN_INVITATION_CREATED]:
    AuditUserActions.INVITATION_ISSUED,
  [AuditActions.ADMIN_INVITATION_RESENT]: AuditUserActions.INVITATION_RESENT,
  [AuditActions.ADMIN_INVITATION_ACCEPTED]: AuditUserActions.ACTIVATED,
  [AuditActions.ADMIN_INVITATION_ACCEPT_FAILED]:
    AuditUserActions.ACTIVATION_FAILED,
  [AuditActions.ADMIN_LOGIN_SUCCESS]: AuditUserActions.LOGIN_SUCCEEDED,
  [AuditActions.ADMIN_LOGIN_FAILED]: AuditUserActions.LOGIN_FAILED,
  [AuditActions.ACCOUNT_LOCKED]: AuditUserActions.ACCOUNT_LOCKED,
  [AuditActions.ACCOUNT_UNLOCKED]: AuditUserActions.ACCOUNT_UNLOCKED,
  [AuditActions.USER_CREATED]: AuditUserActions.EXECUTED,
  [AuditActions.USER_ROLE_BINDING_UPDATED]:
    AuditUserActions.ROLE_BINDINGS_UPDATED,
  [AuditActions.AUDIT_EVIDENCE_EXPORT_REQUESTED]:
    AuditUserActions.REQUEST_CREATED,
  [AuditActions.AUDIT_EVIDENCE_PACKAGE_EXPORTED]: AuditUserActions.EXPORTED,
  [AuditActions.AUDIT_EVIDENCE_PACKAGE_DOWNLOADED]:
    AuditUserActions.DOWNLOADED,
} as const;

function normalizePart(value: string): string {
  return String(value || '')
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase();
}

export function buildStateTransitionAction(
  entity: string,
  fromStatus: string,
  toStatus: string,
): string {
  const entityPart = normalizePart(entity);
  const fromPart = normalizePart(fromStatus);
  const toPart = normalizePart(toStatus);
  return `${entityPart}_${fromPart}_TO_${toPart}`;
}

export function mapRawAuditActionToUserAction(
  action: string,
): (typeof AuditUserActions)[keyof typeof AuditUserActions] | undefined {
  return AuditRawActionToUserActionMap[
    action as keyof typeof AuditRawActionToUserActionMap
  ];
}

// ───── Spec #4: INTERNAL_FUND state → short-name action mapping
const INTERNAL_FUND_STATE_TO_ACTION: Record<string, string> = {
  CREATED: 'CREATED',
  SIGNING: 'SIGNING',
  BROADCASTED: 'BROADCASTED',
  CONFIRMING: 'CONFIRMING',
  CONFIRMED: 'CONFIRMED',
  CLEAR: 'CLEARED',
  FAILED: 'FAILED',
  TIMEOUT: 'TIMED_OUT',
  CANCELLED: 'CANCELLED',
  RETURNED: 'REORGED',
};

/**
 * Map INTERNAL_FUND state-machine target status to a short verb-past audit action.
 * Falls back to UPPERCASE status string for any unmapped value (forward-compat).
 */
export function buildInternalFundStateAction(nextStatus: string): string {
  return (
    INTERNAL_FUND_STATE_TO_ACTION[nextStatus] ?? nextStatus.toUpperCase()
  );
}

import { AuditCorrelationMode } from '../dto/audit-log.dto';

/** V1 治理四域，声明与下方 assertActionSpec 的退役码放行闸共用同一份 */
export const V1_ACTION_DOMAINS = ['IAM', 'APPROVAL', 'CONFIG', 'AUDIT'] as const;
/** 新合同已入住的全部域——站1b-β 起交易域逐域加入（充值第一个）。机器校验的域闸读这份。 */
export const CONTRACT_ACTION_DOMAINS = [...V1_ACTION_DOMAINS, 'DEPOSIT'] as const;

export interface AuditActionSpec {
  /** actionDomain 列的值 */
  domain: (typeof CONTRACT_ACTION_DOMAINS)[number];
  /** 开启还是延续旅程——码的固有属性，不随场景变 */
  correlationMode: AuditCorrelationMode;
  /** 该码特有的必填字段（通用必填不在此列） */
  requiredFields: string[];
  /** 异步驱动的码必须带 causationId */
  requiresCausation: boolean;
}

const S = AuditCorrelationMode.START;
const I = AuditCorrelationMode.INHERIT;
const N = AuditCorrelationMode.NONE;

/**
 * V1 治理底座动作词表 —— 45 码，扁平全局唯一，前缀优先命名。
 * 每码出生即定死：新增码时必须当场声明四件事，不允许「先上线回头补」。
 * 一旦有记录用某码写入，再补必填规则时那些历史记录永远残缺且改不了（只增不改）。
 */
export const V1_AUDIT_ACTIONS: Record<string, AuditActionSpec> = {
  // ── 横切 · 审批引擎（8 个工作流共用）────────────────────────
  APPROVAL_SUBMITTED:  { domain: 'APPROVAL', correlationMode: I, requiredFields: ['policyCode', 'policyVersion'], requiresCausation: false },
  APPROVAL_GRANTED:    { domain: 'APPROVAL', correlationMode: I, requiredFields: ['approvalNo'], requiresCausation: false },
  APPROVAL_DECLINED:   { domain: 'APPROVAL', correlationMode: I, requiredFields: ['approvalNo', 'reason'], requiresCausation: false },
  APPROVAL_CANCELLED:  { domain: 'APPROVAL', correlationMode: I, requiredFields: ['approvalNo', 'reason'], requiresCausation: false },
  APPROVAL_EXPIRED:    { domain: 'APPROVAL', correlationMode: I, requiredFields: ['approvalNo'], requiresCausation: false },
  APPROVAL_SOD_DENIED: { domain: 'APPROVAL', correlationMode: I, requiredFields: ['reasonCode'], requiresCausation: false },

  // ── ① 入职邀请 ──────────────────────────────────────────
  ADMIN_INVITE_REQUESTED:  { domain: 'IAM', correlationMode: S, requiredFields: ['afterData'], requiresCausation: false },
  ADMIN_INVITE_DISPATCHED: { domain: 'IAM', correlationMode: I, requiredFields: [], requiresCausation: false },
  ADMIN_INVITE_ACCEPTED:   { domain: 'IAM', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },
  ADMIN_INVITE_EXPIRED:    { domain: 'IAM', correlationMode: I, requiredFields: [], requiresCausation: false },
  ADMIN_INVITE_CANCELLED:  { domain: 'IAM', correlationMode: I, requiredFields: ['reason'], requiresCausation: false },

  // ── ② 首次登录（四步）───────────────────────────────────
  ADMIN_FIRST_LOGIN_IDENTITY_CONFIRMED: { domain: 'IAM', correlationMode: S, requiredFields: ['authnMethod'], requiresCausation: false },
  ADMIN_FIRST_LOGIN_MFA_INITIATED:      { domain: 'IAM', correlationMode: I, requiredFields: [], requiresCausation: false },
  ADMIN_FIRST_LOGIN_MFA_BOUND:          { domain: 'IAM', correlationMode: I, requiredFields: ['authnMethod'], requiresCausation: false },
  ADMIN_FIRST_LOGIN_COMPLETED:          { domain: 'IAM', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },

  // ── ③ 角色绑定变更 ──────────────────────────────────────
  ADMIN_ROLE_CHANGE_REQUESTED: { domain: 'IAM', correlationMode: S, requiredFields: [], requiresCausation: false },
  ADMIN_ROLE_CHANGE_APPLIED:   { domain: 'IAM', correlationMode: I, requiredFields: ['beforeData', 'afterData', 'approvalNo'], requiresCausation: true },
  ADMIN_ROLE_CHANGE_CANCELLED: { domain: 'IAM', correlationMode: I, requiredFields: ['reason'], requiresCausation: true },

  // ── ④⑤ 停用 / 恢复（代码里无取消路径，刻意不加 CANCELLED）──
  ADMIN_SUSPENSION_REQUESTED:   { domain: 'IAM', correlationMode: S, requiredFields: ['reason'], requiresCausation: false },
  ADMIN_SUSPENSION_APPLIED:     { domain: 'IAM', correlationMode: I, requiredFields: ['fromStatus', 'toStatus', 'approvalNo'], requiresCausation: true },
  ADMIN_REACTIVATION_REQUESTED: { domain: 'IAM', correlationMode: S, requiredFields: ['reason'], requiresCausation: false },
  ADMIN_REACTIVATION_APPLIED:   { domain: 'IAM', correlationMode: I, requiredFields: ['fromStatus', 'toStatus', 'approvalNo'], requiresCausation: true },

  // ── ⑥ 密码重置（自助 / 官员代操作两条路各自成链）──────────
  ADMIN_PASSWORD_RESET_SELF_REQUESTED:    { domain: 'IAM', correlationMode: S, requiredFields: [], requiresCausation: false },
  ADMIN_PASSWORD_RESET_SELF_TOKEN_ISSUED: { domain: 'IAM', correlationMode: I, requiredFields: [], requiresCausation: false },
  ADMIN_PASSWORD_RESET_SELF_COMPLETED:    { domain: 'IAM', correlationMode: I, requiredFields: [], requiresCausation: false },
  ADMIN_PASSWORD_RESET_OFFICER_REQUESTED: { domain: 'IAM', correlationMode: S, requiredFields: ['onBehalfOfNo'], requiresCausation: false },
  ADMIN_PASSWORD_RESET_OFFICER_APPLIED:   { domain: 'IAM', correlationMode: I, requiredFields: ['onBehalfOfNo', 'approvalNo'], requiresCausation: true },
  ADMIN_PASSWORD_RESET_CANCELLED:         { domain: 'IAM', correlationMode: I, requiredFields: ['reason'], requiresCausation: false },

  // ── ⑦ MFA 重置 ─────────────────────────────────────────
  ADMIN_MFA_RESET_REQUESTED: { domain: 'IAM', correlationMode: S, requiredFields: ['onBehalfOfNo'], requiresCausation: false },
  ADMIN_MFA_RESET_APPLIED:   { domain: 'IAM', correlationMode: I, requiredFields: ['fromStatus', 'toStatus', 'approvalNo'], requiresCausation: true },
  ADMIN_MFA_RESET_CANCELLED: { domain: 'IAM', correlationMode: I, requiredFields: ['reason'], requiresCausation: true },

  // ── ⑧ 账号锁定 / 解锁（业主裁定：连续失败自动锁定算业务审计）─
  ADMIN_ACCOUNT_LOCK_APPLIED:  { domain: 'IAM', correlationMode: S, requiredFields: ['reasonCode', 'fromStatus', 'toStatus'], requiresCausation: false },
  ADMIN_ACCOUNT_LOCK_RELEASED: { domain: 'IAM', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },

  // ── ⑨ 角色定义（建 / 改）────────────────────────────────
  ROLE_DEFINITION_CREATE_REQUESTED: { domain: 'CONFIG', correlationMode: S, requiredFields: ['afterData'], requiresCausation: false },
  ROLE_DEFINITION_CREATE_APPLIED:   { domain: 'CONFIG', correlationMode: I, requiredFields: ['afterData', 'approvalNo'], requiresCausation: true },
  ROLE_DEFINITION_CREATE_CANCELLED: { domain: 'CONFIG', correlationMode: I, requiredFields: ['reason'], requiresCausation: true },
  ROLE_DEFINITION_MODIFY_REQUESTED: { domain: 'CONFIG', correlationMode: S, requiredFields: ['beforeData', 'afterData'], requiresCausation: false },
  ROLE_DEFINITION_MODIFY_APPLIED:   { domain: 'CONFIG', correlationMode: I, requiredFields: ['beforeData', 'afterData', 'approvalNo'], requiresCausation: true },
  ROLE_DEFINITION_MODIFY_CANCELLED: { domain: 'CONFIG', correlationMode: I, requiredFields: ['reason'], requiresCausation: true },

  // ── ⑩ 审批策略变更（改策略自身走策略自己审批）──────────────
  APPROVAL_POLICY_CHANGE_REQUESTED: { domain: 'CONFIG', correlationMode: S, requiredFields: ['beforeData', 'afterData'], requiresCausation: false },
  APPROVAL_POLICY_CHANGE_APPLIED:   { domain: 'CONFIG', correlationMode: I, requiredFields: ['beforeData', 'afterData', 'policyVersion', 'approvalNo'], requiresCausation: true },

  // ── ⑪ 审计日志自身的操作 ────────────────────────────────
  AUDIT_EVIDENCE_EXPORT_REQUESTED:  { domain: 'AUDIT', correlationMode: S, requiredFields: [], requiresCausation: false },
  AUDIT_EVIDENCE_EXPORT_GENERATED:  { domain: 'AUDIT', correlationMode: I, requiredFields: ['payloadDigest'], requiresCausation: true },
  AUDIT_EVIDENCE_EXPORT_DOWNLOADED: { domain: 'AUDIT', correlationMode: I, requiredFields: ['sourceIp'], requiresCausation: false },
  AUDIT_LOG_QUERIED:                { domain: 'AUDIT', correlationMode: N, requiredFields: [], requiresCausation: false },
};

/**
 * 退役码：标记 deprecated、不再允许新写入、历史仍可读。不是删除。
 * 7 个 *_FAILED 收编进 outcome=FAILED + reasonCode；4 个登录码归安全日志（③）。
 *
 * ⚠️ 这些都是老命名法裸词，不是扁平全局唯一——'CHANGE_APPLY_FAILED' 同时还被
 * TRANSACTION_LIMIT_CHANGE / SWAP_FEE_LEVEL_CHANGE / WITHDRAWAL_FEE_LEVEL_CHANGE
 * 三个保留（非 V1）域复用，且全部 11 个码此刻仍有真实调用方在写（迁移是 Task 5-9 的事）。
 * 因此 assertActionSpec 里对这份名单的拦截刻意加了 actionDomain 网关，见该方法注释。
 */
/**
 * 充值域名册（站1b-β，2026-08-26，业主终审版 31 码）。
 * 设计稿：doc-final/superpowers/specs/2026-08-26-deposit-audit-vocab-design.md
 * 要点：*_FAILED 不铸码（outcome+reasonCode 表达）；「放行」一码四态
 * （成功/翻案走 from 列/冻结拒批 DENIED/记账失败 FAILED）；动态迁移码族废除
 * （状态变化进 from/to 两列）；三停摆一名三因；一笔充值一段旅程
 * （CREATED=START 铸号落单，其余 INHERIT）。
 */
export const V4_DEPOSIT_AUDIT_ACTIONS: Record<string, AuditActionSpec> = {
  // ── 主线（6）──────────────────────────────────────────────
  DEPOSIT_CREATED:        { domain: 'DEPOSIT', correlationMode: S, requiredFields: ['amount', 'currency', 'ownerCustomerNo'], requiresCausation: false },
  DEPOSIT_PAYIN_COMPLETED:{ domain: 'DEPOSIT', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },
  DEPOSIT_HELD:           { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['reasonCode'], requiresCausation: false },
  DEPOSIT_SUMSUB_SUBMITTED:{ domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_APPROVED:       { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },
  DEPOSIT_LIMIT_WAIVED:   { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['reason'], requiresCausation: false },
  // ── 裁决与复核（5）────────────────────────────────────────
  DEPOSIT_ONHOLD:         { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_MANUAL_CHECKING:{ domain: 'DEPOSIT', correlationMode: I, requiredFields: ['reasonCode'], requiresCausation: false },
  DEPOSIT_FROZEN:         { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },
  DEPOSIT_ACTION_REQUIRED:{ domain: 'DEPOSIT', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },
  DEPOSIT_KYT_VERDICT_IGNORED: { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['reason'], requiresCausation: false },
  // ── 处置四弧（17）────────────────────────────────────────
  DEPOSIT_CONFISCATION_REQUESTED: { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_RETURN_REQUESTED:       { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_SEIZE_REQUESTED:        { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_UNFREEZE_REQUESTED:     { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_CONFISCATION_STARTED:   { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['approvalNo'], requiresCausation: true },
  DEPOSIT_RETURN_STARTED:         { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['approvalNo'], requiresCausation: true },
  DEPOSIT_SEIZE_STARTED:          { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['approvalNo'], requiresCausation: true },
  DEPOSIT_CONFISCATION_RETRIED:   { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_RETURN_RETRIED:         { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_SEIZE_RETRIED:          { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_CONFISCATION_EXECUTED:  { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },
  DEPOSIT_RETURNED:               { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },
  DEPOSIT_SEIZED:                 { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['fromStatus', 'toStatus'], requiresCausation: false },
  DEPOSIT_CONFISCATION_STUCK:     { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_RETURN_STUCK:           { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_SEIZE_STUCK:            { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_UNFROZEN:               { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['approvalNo'], requiresCausation: true },
  // ── SLA 与演示（3）───────────────────────────────────────
  DEPOSIT_SLA_BREACHED:           { domain: 'DEPOSIT', correlationMode: I, requiredFields: ['fromStatus'], requiresCausation: false },
  DEPOSIT_SLA_TIMEOUT_SIMULATED:  { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
  DEPOSIT_DEMO_SCENARIO_RUN:      { domain: 'DEPOSIT', correlationMode: I, requiredFields: [], requiresCausation: false },
};

/** 动态迁移码族（DEPOSIT_<从>_TO_<到>，站1b-β 整族废除）——机器校验按此形状拒写。 */
export const RETIRED_DYNAMIC_TRANSITION_PATTERN = /^DEPOSIT_[A-Z_]+_TO_[A-Z_]+$/;

export const DEPRECATED_AUDIT_ACTIONS: readonly string[] = [
  'FIRST_LOGIN_MFA_VERIFY_FAILED',
  // ── 充值域（站1b-β，2026-08-26）──────────────────────────
  'DEPOSIT_GATE', 'DEPOSIT_HELD_BELOW_MIN', 'DEPOSIT_HELD_NOT_TRADING_READY',
  'DEPOSIT_PAYIN_CONFIRMED', 'DEPOSIT_PAYIN_FAILED', 'DEPOSIT_COMPLETED',
  'DEPOSIT_COMPLIANCE_STARTED', 'DEPOSIT_MANUAL_APPROVED', 'DEPOSIT_APPROVE_BLOCKED_FROZEN',
  'DEPOSIT_ACCOUNTING_BLOCKED', 'DEPOSIT_AWAITUSER_EMPTY_ACTIONS',
  'DEPOSIT_SANCTION_HIT_ON_IGNORED_VERDICT', 'DEPOSIT_CONFISCATION_FAILED',
  'DEPOSIT_CONFISCATION_UNLOCK_FAILED', 'DEPOSIT_RETURN_APPROVAL_REQUESTED',
  'DEPOSIT_SEIZE_APPROVAL_REQUESTED', 'DEPOSIT_UNFREEZE_APPROVAL_REQUESTED',
  'DEPOSIT_LEG_CLEAR_FAILED',
  'RESET_FAILED',
  'CHANGE_APPLY_FAILED',
  'ROLE_ACTIVATE_FAILED',
  'ROLE_MODIFY_FAILED',
  'MODIFICATION_APPLY_FAILED',
  'GENERATION_FAILED',
  'ADMIN_LOGIN_SUCCESS',
  'ADMIN_LOGIN_FAILED',
  'MFA_LOGIN_VERIFIED',
  'MFA_LOGIN_VERIFY_FAILED',
] as const;
