export const WithdrawEvents = {
  EVT_WITHDRAWAL_CREATED: 'EVT_WITHDRAWAL_CREATED',
  EVT_WITHDRAWAL_CANCELLED: 'EVT_WITHDRAWAL_CANCELLED',
  EVT_WITHDRAWAL_REJECTED: 'EVT_WITHDRAWAL_REJECTED',
  EVT_WITHDRAWAL_APPROVED__CRYPTO: 'EVT_WITHDRAWAL_APPROVED__CRYPTO',
  EVT_WITHDRAWAL_SUCCESS__CRYPTO: 'EVT_WITHDRAWAL_SUCCESS__CRYPTO',
  EVT_WITHDRAWAL_FAILED: 'EVT_WITHDRAWAL_FAILED',
  EVT_WITHDRAWAL_APPROVED__FIAT: 'EVT_WITHDRAWAL_APPROVED__FIAT',
  EVT_WITHDRAWAL_SUCCESS__FIAT: 'EVT_WITHDRAWAL_SUCCESS__FIAT',
  EVT_WITHDRAWAL_RETURNED__FIAT: 'EVT_WITHDRAWAL_RETURNED__FIAT',
} as const;

export type WithdrawEventType = (typeof WithdrawEvents)[keyof typeof WithdrawEvents];
