export const DEFAULT_CLEARING_TEMPLATES = [
  {
    code: 'WITHDRAWAL_STANDARD_V1',
    clearingType: 'WITHDRAWAL',
    sourceType: 'WITHDRAWAL',
    description: '标准提现清分模板：全额拆分为客户净出账与平台服务手续费',
    isEnabled: true,
    feeMethod: 'CONFIGURED_FEE',
    outAssetSource: 'src.assetId',
    outAmountSource: 'src.amount',
    inAssetSource: 'src.assetId',
    inAmountSource: 'src.netAmount',
    feeAssetSource: 'src.assetId',
    feeAmountSource: 'src.feeAmount',
    lineTemplates: [
      {
        lineNo: 1,
        lineType: 'FEE',
        partyType: 'PLATFORM',
        assetSource: 'src.assetId',
        amountSource: 'src.feeAmount',
      },
      {
        lineNo: 2,
        lineType: 'OUTGOING',
        partyType: 'CUSTOMER',
        partyIdSource: 'src.ownerId',
        assetSource: 'src.assetId',
        amountSource: 'src.netAmount',
      }
    ],
  },
  {
    code: 'INTERNAL_TX_COLLECTION_V1',
    clearingType: 'INTERNAL_COLLECTION',
    sourceType: 'INTERNAL_TX',
    description: '内部调拨清分模板：总额拆分为净额与网络费',
    isEnabled: true,
    feeMethod: 'ACTUAL_FEE',
    outAssetSource: 'src.assetId',
    outAmountSource: 'src.amount',
    inAssetSource: 'src.assetId',
    inAmountSource: 'src.netAmount',
    feeAssetSource: 'src.assetId',
    feeAmountSource: 'src.feeAmount',
    lineTemplates: [
      {
        lineNo: 1,
        lineType: 'OUTGOING',
        partyType: 'PLATFORM',
        assetSource: 'src.assetId',
        amountSource: 'src.netAmount',
      },
      {
        lineNo: 2,
        lineType: 'FEE',
        partyType: 'PLATFORM',
        assetSource: 'src.assetId',
        amountSource: 'src.feeAmount',
      },
    ],
  },
];
