export const DEFAULT_ACCT_EVENTS = [
  // 1. Deposit Confirmed (Crypto)
  {
    eventCode: 'EVT_DEPOSIT_CONFIRMED__CRYPTO',
    entityType: 'DEPOSIT',
    ownerScope: 'CUSTOMER',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'COMPLIANCE_PENDING',
    description: '充值确认（币）：受限托管入账 + 客户待审负债',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
  },
  // 2. Deposit Success (Crypto)
  {
    eventCode: 'EVT_DEPOSIT_SUCCESS__CRYPTO',
    entityType: 'DEPOSIT',
    ownerScope: 'CUSTOMER',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    description: '充值成功（币）：待审→可用；受限托管→托管',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
  },
  // 3. Deposit Confirmed (Fiat)
  {
    eventCode: 'EVT_DEPOSIT_CONFIRMED__FIAT',
    entityType: 'DEPOSIT',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'COMPLIANCE_PENDING',
    description: '充值确认（法币）：受限银行入账 + 客户待审负债',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
  },
  // 4. Deposit Success (Fiat)
  {
    eventCode: 'EVT_DEPOSIT_SUCCESS__FIAT',
    entityType: 'DEPOSIT',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    description: '充值成功（法币）：待审→可用；受限银行→银行',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
  },
  // 5. Swap Created
  {
    eventCode: 'EVT_SWAP_CREATED',
    entityType: 'SWAP',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'PENDING_COMPLIANCE',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '兑换创建：锁定客户卖出资产（CREDIT → HELD）',
  },
  // 6. Swap Rejected
  {
    eventCode: 'EVT_SWAP_REJECTED',
    entityType: 'SWAP',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null, // Allow rejection from any intermediate status
    toStatus: 'REJECTED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_SWAP_CREATED',
    clearingMode: 'NONE',
    isActive: true,
    description: '兑换拒绝：释放锁定（HELD → CREDIT）',
  },
  // 7. Swap Success
  {
    eventCode: 'EVT_SWAP_SUCCESS',
    entityType: 'SWAP',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null, // Allow success from any intermediate status
    toStatus: 'SUCCESS',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '兑换成功：消耗锁定(from) 并增加可用(to)',
  },
  // 8. Withdrawal Created
  {
    eventCode: 'EVT_WITHDRAWAL_CREATED',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'CREATED',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现创建：锁定客户可用资产 (CREDIT → HELD)',
  },
  // 9. Withdrawal Approved (Crypto)
  {
    eventCode: 'EVT_WITHDRAWAL_APPROVED__CRYPTO',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'PAYOUT_PENDING',
    postingMode: 'TEMPLATE', 
    clearingMode: 'TEMPLATE',
    clearingTemplateCode: 'WITHDRAWAL_STANDARD_V1',
    isActive: true,
    description: '提现审批（币）：触发清算并进入在途资产',
  },
  // 10. Withdrawal Approved (Fiat)
  {
    eventCode: 'EVT_WITHDRAWAL_APPROVED__FIAT',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'PAYOUT_PENDING',
    postingMode: 'TEMPLATE',
    clearingMode: 'TEMPLATE',
    clearingTemplateCode: 'WITHDRAWAL_STANDARD_V1',
    isActive: true,
    description: '提现审批（法币）：触发清算并进入在途资产',
  },
  // 11. Withdrawal Success (Crypto)
  {
    eventCode: 'EVT_WITHDRAWAL_SUCCESS__CRYPTO',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现成功（币）：消耗锁定资产',
  },
  // 12. Withdrawal Success (Fiat)
  {
    eventCode: 'EVT_WITHDRAWAL_SUCCESS__FIAT',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现成功（法币）：消耗锁定资产',
  },
  // 13. Withdrawal Failed (Crypto)
  {
    eventCode: 'EVT_WITHDRAWAL_FAILED__CRYPTO',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'FAILED',
    postingMode: 'BULK_REVERSAL_BY_SOURCE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现失败（币）：冲销该提现单全部记账',
  },
  // 14. Withdrawal Failed (Fiat)
  {
    eventCode: 'EVT_WITHDRAWAL_FAILED__FIAT',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'FAILED',
    postingMode: 'BULK_REVERSAL_BY_SOURCE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现失败（法币）：冲销该提现单全部记账',
  },
  // 15. Withdrawal Returned (Fiat)
  {
    eventCode: 'EVT_WITHDRAWAL_RETURNED__FIAT',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'RETURNED',
    postingMode: 'BULK_REVERSAL_BY_SOURCE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现退回：冲销该提现单全部记账',
  },
  // 16. Withdrawal Cancelled/Rejected
  {
    eventCode: 'EVT_WITHDRAWAL_CANCELLED',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'CANCELLED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_WITHDRAWAL_CREATED',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现取消：冲销锁定',
  },
  {
    eventCode: 'EVT_WITHDRAWAL_REJECTED',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'REJECTED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_WITHDRAWAL_CREATED',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现拒绝：冲销锁定',
  },
];
