export const DEFAULT_ACCT_EVENTS = [
  // 1. Deposit Confirmed (Crypto)
  {
    eventCode: 'EVT_DEPOSIT_CONFIRMED__CRYPTO',
    entityType: 'DEPOSIT',
    ownerScope: 'CUSTOMER',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'COMPLIANCE_PENDING',
    description: '充值确认（币）：受限托管入账 + 客户待审负债',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
  },
  // 2. Deposit Success (Crypto)
  {
    eventCode: 'EVT_DEPOSIT_SUCCESS__CRYPTO',
    entityType: 'DEPOSIT',
    ownerScope: 'CUSTOMER',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    description: '充值成功（币）：待审→可用；受限托管→托管',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
  },
  // 3. Deposit Confirmed (Fiat)
  {
    eventCode: 'EVT_DEPOSIT_CONFIRMED__FIAT',
    entityType: 'DEPOSIT',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'COMPLIANCE_PENDING',
    description: '充值确认（法币）：受限银行入账 + 客户待审负债',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
  },
  // 4. Deposit Success (Fiat)
  {
    eventCode: 'EVT_DEPOSIT_SUCCESS__FIAT',
    entityType: 'DEPOSIT',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    description: '充值成功（法币）：待审→可用；受限银行→银行',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
  },
  // 5. Swap Created
  {
    eventCode: 'EVT_SWAP_CREATED',
    entityType: 'SWAP',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'PENDING_COMPLIANCE',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '兑换创建：锁定客户卖出资产（CREDIT → HELD）',
  },
  // 6. Swap Rejected
  {
    eventCode: 'EVT_SWAP_REJECTED',
    entityType: 'SWAP',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null, // Allow rejection from any intermediate status
    toStatus: 'REJECTED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_SWAP_CREATED',
    clearingMode: 'NONE',
    isActive: true,
    description: '兑换拒绝：释放锁定（HELD → CREDIT）',
  },
  // 7A. Swap Failed
  {
    eventCode: 'EVT_SWAP_FAILED',
    entityType: 'SWAP',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'FAILED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_SWAP_CREATED',
    clearingMode: 'NONE',
    isActive: true,
    description: '兑换失败：释放锁定（HELD → CREDIT）并终止交易',
  },
  // 7. Swap Success
  {
    eventCode: 'EVT_SWAP_SUCCESS',
    entityType: 'SWAP',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null, // Allow success from any intermediate status
    toStatus: 'SUCCESS',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '兑换成功：消耗锁定(from) 并增加可用(to)',
  },
  // 8. Withdrawal Created
  {
    eventCode: 'EVT_WITHDRAWAL_CREATED',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'CREATED',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现创建：锁定客户可用资产 (CREDIT → HELD)',
  },
  // 9. Withdrawal Approved (Crypto)
  {
    eventCode: 'EVT_WITHDRAWAL_APPROVED__CRYPTO',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'PAYOUT_PENDING',
    postingMode: 'TEMPLATE', 
    clearingMode: 'TEMPLATE',
    clearingTemplateCode: 'WITHDRAWAL_STANDARD_V1',
    isActive: true,
    description: '提现审批（币）：触发清算并进入在途资产',
  },
  // 10. Withdrawal Approved (Fiat)
  {
    eventCode: 'EVT_WITHDRAWAL_APPROVED__FIAT',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'PAYOUT_PENDING',
    postingMode: 'TEMPLATE',
    clearingMode: 'TEMPLATE',
    clearingTemplateCode: 'WITHDRAWAL_STANDARD_V1',
    isActive: true,
    description: '提现审批（法币）：触发清算并进入在途资产',
  },
  // 11. Withdrawal Success (Crypto)
  {
    eventCode: 'EVT_WITHDRAWAL_SUCCESS__CRYPTO',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现成功（币）：消耗锁定资产',
  },
  // 12. Withdrawal Success (Fiat)
  {
    eventCode: 'EVT_WITHDRAWAL_SUCCESS__FIAT',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现成功（法币）：消耗锁定资产',
  },
  // 13. Withdrawal Failed
  {
    eventCode: 'EVT_WITHDRAWAL_FAILED',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'FAILED',
    postingMode: 'BULK_REVERSAL_BY_SOURCE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现失败：冲销该提现单全部记账',
  },
  // 15. Withdrawal Returned (Fiat)
  {
    eventCode: 'EVT_WITHDRAWAL_RETURNED__FIAT',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'RETURNED',
    postingMode: 'BULK_REVERSAL_BY_SOURCE',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现退回：冲销该提现单全部记账',
  },
  // 16. Withdrawal Cancelled/Rejected
  {
    eventCode: 'EVT_WITHDRAWAL_CANCELLED',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'CANCELLED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_WITHDRAWAL_CREATED',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现取消：冲销锁定',
  },
  {
    eventCode: 'EVT_WITHDRAWAL_REJECTED',
    entityType: 'WITHDRAW',
    ownerScope: 'CUSTOMER',
    assetType: 'ALL',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'REJECTED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_WITHDRAWAL_CREATED',
    clearingMode: 'NONE',
    isActive: true,
    description: '提现拒绝：冲销锁定',
  },
  // 17. Internal Transaction Created (Crypto Internal Transfer)
  {
    eventCode: 'EVT_INTERNAL_TX_CREATED__CRYPTO',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'INTERNAL_FUNDS_PENDING',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '内部调拨创建：可用资产转入在途',
  },
  // 18. Internal Transaction Success (Crypto Internal Transfer)
  {
    eventCode: 'EVT_INTERNAL_TX_SUCCESS__CRYPTO',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    postingMode: 'TEMPLATE',
    clearingMode: 'TEMPLATE',
    clearingTemplateCode: 'INTERNAL_TX_COLLECTION_V1',
    isActive: true,
    description: '内部调拨成功：在途回到目标托管，并记录网络费',
  },
  // 19. Internal Transaction Failed
  {
    eventCode: 'EVT_INTERNAL_TX_FAILED__CRYPTO',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'FAILED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_INTERNAL_TX_CREATED__CRYPTO',
    clearingMode: 'NONE',
    isActive: true,
    description: '内部调拨失败：冲回创建分录',
  },
  // 20. Internal Transaction Cancelled
  {
    eventCode: 'EVT_INTERNAL_TX_CANCELLED__CRYPTO',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'CANCELLED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_INTERNAL_TX_CREATED__CRYPTO',
    clearingMode: 'NONE',
    isActive: true,
    description: '内部调拨取消：冲回创建分录',
  },
  // 21. Internal Transaction Rejected
  {
    eventCode: 'EVT_INTERNAL_TX_REJECTED__CRYPTO',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'CRYPTO',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'REJECTED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_INTERNAL_TX_CREATED__CRYPTO',
    clearingMode: 'NONE',
    isActive: true,
    description: '内部调拨驳回：冲回创建分录',
  },
  // 22. Internal Transaction Created (Fiat Internal Transfer)
  {
    eventCode: 'EVT_INTERNAL_TX_CREATED__FIAT',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'INTERNAL_FUNDS_PENDING',
    postingMode: 'TEMPLATE',
    clearingMode: 'NONE',
    isActive: true,
    description: '内部调拨创建（法币）：可用资产转入在途',
  },
  // 23. Internal Transaction Success (Fiat Internal Transfer)
  {
    eventCode: 'EVT_INTERNAL_TX_SUCCESS__FIAT',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'SUCCESS',
    postingMode: 'TEMPLATE',
    clearingMode: 'TEMPLATE',
    clearingTemplateCode: 'INTERNAL_TX_COLLECTION_V1',
    isActive: true,
    description: '内部调拨成功（法币）：在途回到目标银行池，并记录银行费',
  },
  // 24. Internal Transaction Failed (Fiat)
  {
    eventCode: 'EVT_INTERNAL_TX_FAILED__FIAT',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'FAILED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_INTERNAL_TX_CREATED__FIAT',
    clearingMode: 'NONE',
    isActive: true,
    description: '内部调拨失败（法币）：冲回创建分录',
  },
  // 25. Internal Transaction Cancelled (Fiat)
  {
    eventCode: 'EVT_INTERNAL_TX_CANCELLED__FIAT',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'CANCELLED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_INTERNAL_TX_CREATED__FIAT',
    clearingMode: 'NONE',
    isActive: true,
    description: '内部调拨取消（法币）：冲回创建分录',
  },
  // 26. Internal Transaction Rejected (Fiat)
  {
    eventCode: 'EVT_INTERNAL_TX_REJECTED__FIAT',
    entityType: 'INTERNAL_TX',
    ownerScope: 'PLATFORM',
    assetType: 'FIAT',
    triggerType: 'STATUS_TRANSITION',
    triggerKey: 'status',
    fromStatus: null,
    toStatus: 'REJECTED',
    postingMode: 'AUTO_REVERSAL',
    postingReversalOfEventCode: 'EVT_INTERNAL_TX_CREATED__FIAT',
    clearingMode: 'NONE',
    isActive: true,
    description: '内部调拨驳回（法币）：冲回创建分录',
  },
];
