export const DEFAULT_JOURNAL_TEMPLATES = [
  // Deposit Confirmed (Crypto)
  {
    header: {
      templateCode: 'TPL_EVT_DEPOSIT_CONFIRMED__CRYPTO_V1',
      eventCode: 'EVT_DEPOSIT_CONFIRMED__CRYPTO',
      version: 1,
      status: 'ACTIVE',
      description: '充值确认（虚拟币）：受限托管入账 + 客户待审负债',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'A.CUSTODY_RESTRICTED',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.walletId}}"}',
        description: '入金确认：虚拟资产进入受限托管',
      },
      {
        lineNo: 2,
        accountCode: 'L.CLIENT_AUDIT',
        drCr: 'CR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.ownerType',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '入金确认：客户资金进入待审负债',
      },
    ],
  },
  // Deposit Success (Crypto)
  {
    header: {
      templateCode: 'TPL_EVT_DEPOSIT_SUCCESS__CRYPTO_V1',
      eventCode: 'EVT_DEPOSIT_SUCCESS__CRYPTO',
      version: 1,
      status: 'ACTIVE',
      description: '充值成功（虚拟币）：待审→可用；受限托管→托管',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'L.CLIENT_AUDIT',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.ownerType',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '入金成功：待审负债转出',
      },
      {
        lineNo: 2,
        accountCode: 'L.CLIENT_CREDIT',
        drCr: 'CR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.ownerType',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '入金成功：客户可用余额增加',
      },
      {
        lineNo: 3,
        accountCode: 'A.CUSTODY',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.walletId}}"}',
        description: '入金成功：托管可用资产增加',
      },
      {
        lineNo: 4,
        accountCode: 'A.CUSTODY_RESTRICTED',
        drCr: 'CR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.walletId}}"}',
        description: '入金成功：受限托管资产转出',
      },
    ],
  },
  // Deposit Confirmed (Fiat)
  {
    header: {
      templateCode: 'TPL_EVT_DEPOSIT_CONFIRMED__FIAT_V1',
      eventCode: 'EVT_DEPOSIT_CONFIRMED__FIAT',
      version: 1,
      status: 'ACTIVE',
      description: '充值确认（法币）：受限银行入账 + 客户待审负债',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'A.BANK_RESTRICTED',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.walletId}}"}',
        description: '入金确认：法币进入受限银行',
      },
      {
        lineNo: 2,
        accountCode: 'L.CLIENT_AUDIT',
        drCr: 'CR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.ownerType',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '入金确认：客户资金进入待审负债',
      },
    ],
  },
  // Deposit Success (Fiat)
  {
    header: {
      templateCode: 'TPL_EVT_DEPOSIT_SUCCESS__FIAT_V1',
      eventCode: 'EVT_DEPOSIT_SUCCESS__FIAT',
      version: 1,
      status: 'ACTIVE',
      description: '充值成功（法币）：待审→可用；受限银行→银行',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'L.CLIENT_AUDIT',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.ownerType',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '入金成功：待审负债转出',
      },
      {
        lineNo: 2,
        accountCode: 'L.CLIENT_CREDIT',
        drCr: 'CR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.ownerType',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '入金成功：客户可用余额增加',
      },
      {
        lineNo: 3,
        accountCode: 'A.BANK',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.walletId}}"}',
        description: '入金成功：银行可用资产增加',
      },
      {
        lineNo: 4,
        accountCode: 'A.BANK_RESTRICTED',
        drCr: 'CR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.walletId}}"}',
        description: '入金成功：受限银行资产转出',
      },
    ],
  },
  // Swap Created
  {
    header: {
      templateCode: 'TPL_EVT_SWAP_CREATED_V1',
      eventCode: 'EVT_SWAP_CREATED',
      version: 1,
      status: 'ACTIVE',
      description: '兑换创建：锁定客户卖出资产（CREDIT → HELD）',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'L.CLIENT_CREDIT',
        drCr: 'DR',
        amountSource: 'FROM_AMOUNT',
        assetSource: 'FROM_ASSET_ID',
        ownerTypeSource: 'CUSTOMER',
        ownerIdSource: 'src.ownerId',
        referenceSource: 'src.swapNo',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.fromAssetId}}"}',
        description: '锁定：客户可用余额减少（卖出资产）',
      },
      {
        lineNo: 2,
        accountCode: 'L.CLIENT_HELD',
        drCr: 'CR',
        amountSource: 'FROM_AMOUNT',
        assetSource: 'FROM_ASSET_ID',
        ownerTypeSource: 'CUSTOMER',
        ownerIdSource: 'src.ownerId',
        referenceSource: 'src.swapNo',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.fromAssetId}}"}',
        description: '锁定：客户冻结余额增加（卖出资产）',
      },
    ],
  },
  // Swap Success
  {
    header: {
      templateCode: 'TPL_EVT_SWAP_SUCCESS_V1',
      eventCode: 'EVT_SWAP_SUCCESS',
      version: 1,
      status: 'ACTIVE',
      description: '兑换成功：消耗锁定(from) + 与流动性对手结算 + 增加可用(to)',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'L.CLIENT_HELD',
        drCr: 'DR',
        amountSource: 'FROM_AMOUNT',
        assetSource: 'FROM_ASSET_ID',
        ownerTypeSource: 'CUSTOMER',
        ownerIdSource: 'src.ownerId',
        fxRateSource: 'src.exchangeRate',
        referenceSource: 'src.swapNo',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.fromAssetId}}"}',
        description: '成交：消耗冻结余额（卖出资产）',
      },
      {
        lineNo: 2,
        accountCode: 'L.LP_PAYABLE',
        drCr: 'CR',
        amountSource: 'FROM_AMOUNT',
        assetSource: 'FROM_ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        fxRateSource: 'src.exchangeRate',
        referenceSource: 'src.swapNo',
        dimensionsRule: '{"assetId":"{{src.fromAssetId}}"}',
        description: '成交：记录对流动性对手的应付（卖出资产）',
      },
      {
        lineNo: 3,
        accountCode: 'L.LP_PAYABLE',
        drCr: 'DR',
        amountSource: 'TO_AMOUNT',
        assetSource: 'TO_ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        fxRateSource: 'src.exchangeRate',
        referenceSource: 'src.swapNo',
        dimensionsRule: '{"assetId":"{{src.toAssetId}}"}',
        description: '成交：记录对流动性对手的应收（买入资产）',
      },
      {
        lineNo: 4,
        accountCode: 'L.CLIENT_CREDIT',
        drCr: 'CR',
        amountSource: 'TO_AMOUNT',
        assetSource: 'TO_ASSET_ID',
        ownerTypeSource: 'CUSTOMER',
        ownerIdSource: 'src.ownerId',
        fxRateSource: 'src.exchangeRate',
        referenceSource: 'src.swapNo',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.toAssetId}}"}',
        description: '成交：增加可用余额（买入资产）',
      },
    ],
  },
  // 10. Withdrawal Created
  {
    header: {
      templateCode: 'TPL_EVT_WITHDRAWAL_CREATED_V1',
      eventCode: 'EVT_WITHDRAWAL_CREATED',
      version: 1,
      status: 'ACTIVE',
      description: '提现创建：锁定客户可用资产 (CREDIT → HELD)',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'L.CLIENT_CREDIT',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'CUSTOMER',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '提现锁定：客户可用余额减少',
      },
      {
        lineNo: 2,
        accountCode: 'L.CLIENT_HELD',
        drCr: 'CR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'CUSTOMER',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '提现锁定：客户冻结余额增加',
      },
    ],
  },
  // 11. Withdrawal Approved (Crypto)
  {
    header: {
      templateCode: 'TPL_EVT_WITHDRAWAL_APPROVED__CRYPTO_V1',
      eventCode: 'EVT_WITHDRAWAL_APPROVED__CRYPTO',
      version: 1,
      status: 'ACTIVE',
      description: '提现审批通过（币）：进入在途资产',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'A.CUSTODY_IN_TRANSIT',
        drCr: 'DR',
        amountSource: 'NET_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.fromWalletId}}"}',
        description: '提现审批：资产进入在途托管',
      },
      {
        lineNo: 2,
        accountCode: 'A.CUSTODY',
        drCr: 'CR',
        amountSource: 'NET_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.fromWalletId}}"}',
        description: '提现审批：从托管可用转出',
      },
    ],
  },
  // 12. Withdrawal Approved (Fiat)
  {
    header: {
      templateCode: 'TPL_EVT_WITHDRAWAL_APPROVED__FIAT_V1',
      eventCode: 'EVT_WITHDRAWAL_APPROVED__FIAT',
      version: 1,
      status: 'ACTIVE',
      description: '提现审批通过（法币）：进入在途资产',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'A.BANK_IN_TRANSIT',
        drCr: 'DR',
        amountSource: 'NET_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.fromWalletId}}"}',
        description: '提现审批：资产进入在途银行',
      },
      {
        lineNo: 2,
        accountCode: 'A.BANK',
        drCr: 'CR',
        amountSource: 'NET_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.fromWalletId}}"}',
        description: '提现审批：从银行可用转出',
      },
    ],
  },
  // 13. Withdrawal Success (Crypto)
  {
    header: {
      templateCode: 'TPL_EVT_WITHDRAWAL_SUCCESS__CRYPTO_V1',
      eventCode: 'EVT_WITHDRAWAL_SUCCESS__CRYPTO',
      version: 1,
      status: 'ACTIVE',
      description: '提现成功（币）：核销冻结与在途，记录手续费',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'L.CLIENT_HELD',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'CUSTOMER',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '提现成功：释放并扣减冻结币资产',
      },
      {
        lineNo: 2,
        accountCode: 'A.CUSTODY_IN_TRANSIT',
        drCr: 'CR',
        amountSource: 'NET_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.fromWalletId}}"}',
        description: '提现成功：核销在途资产',
      },
      {
        lineNo: 3,
        accountCode: 'L.PLATFORM_PAYABLE', // Or L.PLATFORM_REVENUE
        drCr: 'CR',
        amountSource: 'FEE_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}"}',
        description: '提现成功：记录平台手续费收入',
      },
    ],
  },
  // 14. Withdrawal Success (Fiat)
  {
    header: {
      templateCode: 'TPL_EVT_WITHDRAWAL_SUCCESS__FIAT_V1',
      eventCode: 'EVT_WITHDRAWAL_SUCCESS__FIAT',
      version: 1,
      status: 'ACTIVE',
      description: '提现成功（法币）：核销冻结与在途，记录手续费',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'L.CLIENT_HELD',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'CUSTOMER',
        ownerIdSource: 'src.ownerId',
        dimensionsRule: '{"client_id":"{{src.ownerId}}","assetId":"{{src.assetId}}"}',
        description: '提现成功：释放并扣减冻结法币资产',
      },
      {
        lineNo: 2,
        accountCode: 'A.BANK_IN_TRANSIT',
        drCr: 'CR',
        amountSource: 'NET_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.fromWalletId}}"}',
        description: '提现成功：核销在途资产',
      },
      {
        lineNo: 3,
        accountCode: 'L.PLATFORM_PAYABLE',
        drCr: 'CR',
        amountSource: 'FEE_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'PLATFORM',
        dimensionsRule: '{"assetId":"{{src.assetId}}"}',
        description: '提现成功：记录平台手续费收入',
      },
    ],
  },
  // 15. Internal Transaction Created (Crypto Internal Transfer)
  {
    header: {
      templateCode: 'TPL_EVT_INTERNAL_TX_CREATED_V1',
      eventCode: 'EVT_INTERNAL_TX_CREATED',
      version: 1,
      status: 'ACTIVE',
      description: '内部调拨创建：可用资产转在途',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'A.CUSTODY_IN_TRANSIT',
        drCr: 'DR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.toWalletOwnerType',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.toWalletId}}","internalTxNo":"{{src.internalTxNo}}"}',
        description: '调拨创建：在途资产增加',
      },
      {
        lineNo: 2,
        accountCode: 'A.CUSTODY',
        drCr: 'CR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.fromWalletOwnerType',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.fromWalletId}}","internalTxNo":"{{src.internalTxNo}}"}',
        description: '调拨创建：来源可用资产减少',
      },
    ],
  },
  // 16. Internal Transaction Success (Crypto Internal Transfer)
  {
    header: {
      templateCode: 'TPL_EVT_INTERNAL_TX_SUCCESS_V1',
      eventCode: 'EVT_INTERNAL_TX_SUCCESS',
      version: 1,
      status: 'ACTIVE',
      description: '内部调拨成功：在途回目标托管并记录网络费',
    },
    lines: [
      {
        lineNo: 1,
        accountCode: 'A.CUSTODY',
        drCr: 'DR',
        amountSource: 'NET_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.toWalletOwnerType',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.toWalletId}}","internalTxNo":"{{src.internalTxNo}}"}',
        description: '调拨成功：目标可用资产增加',
      },
      {
        lineNo: 2,
        accountCode: 'E.NETWORK_FEE',
        drCr: 'DR',
        amountSource: 'FEE_AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.fromWalletOwnerType',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.fromWalletId}}","internalTxNo":"{{src.internalTxNo}}"}',
        description: '调拨成功：记录链上网络费用',
      },
      {
        lineNo: 3,
        accountCode: 'A.CUSTODY_IN_TRANSIT',
        drCr: 'CR',
        amountSource: 'AMOUNT',
        assetSource: 'ASSET_ID',
        ownerTypeSource: 'src.toWalletOwnerType',
        dimensionsRule: '{"assetId":"{{src.assetId}}","walletId":"{{src.toWalletId}}","internalTxNo":"{{src.internalTxNo}}"}',
        description: '调拨成功：核销在途资产',
      },
    ],
  },
];
